default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  socket: /tmp/mysql.sock

development:
  <<: *default
  host: localhost
  database: retail_scraper_dev
  username: scraper
  password: test

test:
  <<: *default
  host: localhost
  database: retail_scraper_test
  username: scraper
  password: test

staging:
  <<: *default
  host: localhost
  database: retail_scraper_staging
  username: dbuser
  password: y0u4staging09db
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  host: localhost
  database: retail_scraper_prod
  username: dbuser
  password: y0u4staging09db
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>