Category.create!([
  {name: "Women's Clothing", level: 1, order_index: 1, parent_category_id: nil, full_path: "Women's Clothing"},
  {name: "Hot Categories", level: 2, order_index: 1, parent_category_id: 549, full_path: "Women's Clothing > Hot Categories"},
  {name: "Dresses", level: 3, order_index: 1, parent_category_id: 550, full_path: "Women's Clothing > Hot Categories > Dresses"},
  {name: "Jackets & Coats", level: 3, order_index: 2, parent_category_id: 550, full_path: "Women's Clothing > Hot Categories > Jackets & Coats"},
  {name: "Sweaters", level: 3, order_index: 3, parent_category_id: 550, full_path: "Women's Clothing > Hot Categories > Sweaters"},
  {name: "Jeans", level: 3, order_index: 4, parent_category_id: 550, full_path: "Women's Clothing > Hot Categories > Jeans"},
  {name: "Suits & Sets", level: 3, order_index: 5, parent_category_id: 550, full_path: "Women's Clothing > Hot Categories > Suits & Sets"},
  {name: "Blouses & Shirts", level: 3, order_index: 6, parent_category_id: 550, full_path: "Women's Clothing > Hot Categories > Blouses & Shirts"},
  {name: "Bottoms", level: 2, order_index: 2, parent_category_id: 549, full_path: "Women's Clothing > Bottoms"},
  {name: "Skirts", level: 3, order_index: 1, parent_category_id: 557, full_path: "Women's Clothing > Bottoms > Skirts"},
  {name: "Leggings", level: 3, order_index: 2, parent_category_id: 557, full_path: "Women's Clothing > Bottoms > Leggings"},
  {name: "Jeans", level: 3, order_index: 3, parent_category_id: 557, full_path: "Women's Clothing > Bottoms > Jeans"},
  {name: "Pants & Capris", level: 3, order_index: 4, parent_category_id: 557, full_path: "Women's Clothing > Bottoms > Pants & Capris"},
  {name: "Wide Leg Pants", level: 3, order_index: 5, parent_category_id: 557, full_path: "Women's Clothing > Bottoms > Wide Leg Pants"},
  {name: "Shorts", level: 3, order_index: 6, parent_category_id: 557, full_path: "Women's Clothing > Bottoms > Shorts"},
  {name: "Outerwear & Jackets", level: 2, order_index: 3, parent_category_id: 549, full_path: "Women's Clothing > Outerwear & Jackets"},
  {name: "Basic Jackets", level: 3, order_index: 1, parent_category_id: 564, full_path: "Women's Clothing > Outerwear & Jackets > Basic Jackets"},
  {name: "Blazers", level: 3, order_index: 2, parent_category_id: 564, full_path: "Women's Clothing > Outerwear & Jackets > Blazers"},
  {name: "Trench Coats", level: 3, order_index: 3, parent_category_id: 564, full_path: "Women's Clothing > Outerwear & Jackets > Trench Coats"},
  {name: "Real Fur", level: 3, order_index: 4, parent_category_id: 564, full_path: "Women's Clothing > Outerwear & Jackets > Real Fur"},
  {name: "Down Coats", level: 3, order_index: 5, parent_category_id: 564, full_path: "Women's Clothing > Outerwear & Jackets > Down Coats"},
  {name: "Parkas", level: 3, order_index: 6, parent_category_id: 564, full_path: "Women's Clothing > Outerwear & Jackets > Parkas"},
  {name: "Tops & Sets", level: 2, order_index: 4, parent_category_id: 549, full_path: "Women's Clothing > Tops & Sets"},
  {name: "Tank Tops", level: 3, order_index: 1, parent_category_id: 571, full_path: "Women's Clothing > Tops & Sets > Tank Tops"},
  {name: "Suits & Sets", level: 3, order_index: 2, parent_category_id: 571, full_path: "Women's Clothing > Tops & Sets > Suits & Sets"},
  {name: "Jumpsuits", level: 3, order_index: 3, parent_category_id: 571, full_path: "Women's Clothing > Tops & Sets > Jumpsuits"},
  {name: "Rompers", level: 3, order_index: 4, parent_category_id: 571, full_path: "Women's Clothing > Tops & Sets > Rompers"},
  {name: "Intimates", level: 3, order_index: 5, parent_category_id: 571, full_path: "Women's Clothing > Tops & Sets > Intimates"},
  {name: "Sleep & Lounge", level: 3, order_index: 6, parent_category_id: 571, full_path: "Women's Clothing > Tops & Sets > Sleep & Lounge"},
  {name: "Weddings & Events", level: 2, order_index: 5, parent_category_id: 549, full_path: "Women's Clothing > Weddings & Events"},
  {name: "Wedding Dresses", level: 3, order_index: 1, parent_category_id: 578, full_path: "Women's Clothing > Weddings & Events > Wedding Dresses"},
  {name: "Evening Dresses", level: 3, order_index: 2, parent_category_id: 578, full_path: "Women's Clothing > Weddings & Events > Evening Dresses"},
  {name: "Mother of the Bride Dresses", level: 3, order_index: 3, parent_category_id: 578, full_path: "Women's Clothing > Weddings & Events > Mother of the Bride Dresses"},
  {name: "Prom Dresses", level: 3, order_index: 4, parent_category_id: 578, full_path: "Women's Clothing > Weddings & Events > Prom Dresses"},
  {name: "Bridesmaid Dresses", level: 3, order_index: 5, parent_category_id: 578, full_path: "Women's Clothing > Weddings & Events > Bridesmaid Dresses"},
  {name: "Wedding Accessories", level: 3, order_index: 6, parent_category_id: 578, full_path: "Women's Clothing > Weddings & Events > Wedding Accessories"},
  {name: "Accessories", level: 2, order_index: 6, parent_category_id: 549, full_path: "Women's Clothing > Accessories"},
  {name: "Eyewear & Accessories", level: 3, order_index: 1, parent_category_id: 585, full_path: "Women's Clothing > Accessories > Eyewear & Accessories"},
  {name: "Hats & Caps", level: 3, order_index: 2, parent_category_id: 585, full_path: "Women's Clothing > Accessories > Hats & Caps"},
  {name: "Belts & Cummerbunds", level: 3, order_index: 3, parent_category_id: 585, full_path: "Women's Clothing > Accessories > Belts & Cummerbunds"},
  {name: "Scarves & Wraps", level: 3, order_index: 4, parent_category_id: 585, full_path: "Women's Clothing > Accessories > Scarves & Wraps"},
  {name: "Gloves & Mittens", level: 3, order_index: 5, parent_category_id: 585, full_path: "Women's Clothing > Accessories > Gloves & Mittens"},
  {name: "Prescription Glasses", level: 3, order_index: 6, parent_category_id: 585, full_path: "Women's Clothing > Accessories > Prescription Glasses"},
  {name: "Men's Clothing", level: 1, order_index: 1, parent_category_id: nil, full_path: "Men's Clothing"},
  {name: "Hot Sale", level: 2, order_index: 1, parent_category_id: 592, full_path: "Men's Clothing > Hot Sale"},
  {name: "Hoodies & Sweatshirts", level: 3, order_index: 1, parent_category_id: 593, full_path: "Men's Clothing > Hot Sale > Hoodies & Sweatshirts"},
  {name: "Jackets", level: 3, order_index: 2, parent_category_id: 593, full_path: "Men's Clothing > Hot Sale > Jackets"},
  {name: "T-Shirts", level: 3, order_index: 3, parent_category_id: 593, full_path: "Men's Clothing > Hot Sale > T-Shirts"},
  {name: "Shirts", level: 3, order_index: 4, parent_category_id: 593, full_path: "Men's Clothing > Hot Sale > Shirts"},
  {name: "Sweaters", level: 3, order_index: 5, parent_category_id: 593, full_path: "Men's Clothing > Hot Sale > Sweaters"},
  {name: "Socks", level: 3, order_index: 6, parent_category_id: 593, full_path: "Men's Clothing > Hot Sale > Socks"},
  {name: "Bottoms", level: 2, order_index: 2, parent_category_id: 592, full_path: "Men's Clothing > Bottoms"},
  {name: "Casual Pants", level: 3, order_index: 1, parent_category_id: 600, full_path: "Men's Clothing > Bottoms > Casual Pants"},
  {name: "Cargo Pants", level: 3, order_index: 2, parent_category_id: 600, full_path: "Men's Clothing > Bottoms > Cargo Pants"},
  {name: "Jeans", level: 3, order_index: 3, parent_category_id: 600, full_path: "Men's Clothing > Bottoms > Jeans"},
  {name: "Sweatpants", level: 3, order_index: 4, parent_category_id: 600, full_path: "Men's Clothing > Bottoms > Sweatpants"},
  {name: "Harem Pants", level: 3, order_index: 5, parent_category_id: 600, full_path: "Men's Clothing > Bottoms > Harem Pants"},
  {name: "Shorts", level: 3, order_index: 6, parent_category_id: 600, full_path: "Men's Clothing > Bottoms > Shorts"},
  {name: "Outerwear & Jackets", level: 2, order_index: 3, parent_category_id: 592, full_path: "Men's Clothing > Outerwear & Jackets"},
  {name: "Trench", level: 3, order_index: 1, parent_category_id: 607, full_path: "Men's Clothing > Outerwear & Jackets > Trench"},
  {name: "Genuine Leather", level: 3, order_index: 2, parent_category_id: 607, full_path: "Men's Clothing > Outerwear & Jackets > Genuine Leather"},
  {name: "Parkas", level: 3, order_index: 3, parent_category_id: 607, full_path: "Men's Clothing > Outerwear & Jackets > Parkas"},
  {name: "Down Jackets", level: 3, order_index: 4, parent_category_id: 607, full_path: "Men's Clothing > Outerwear & Jackets > Down Jackets"},
  {name: "Wool & Blends", level: 3, order_index: 5, parent_category_id: 607, full_path: "Men's Clothing > Outerwear & Jackets > Wool & Blends"},
  {name: "Suits & Blazer", level: 3, order_index: 6, parent_category_id: 607, full_path: "Men's Clothing > Outerwear & Jackets > Suits & Blazer"},
  {name: "Underwear & Night", level: 2, order_index: 4, parent_category_id: 592, full_path: "Men's Clothing > Underwear & Night"},
  {name: "Boxers", level: 3, order_index: 1, parent_category_id: 614, full_path: "Men's Clothing > Underwear & Night > Boxers"},
  {name: "Briefs", level: 3, order_index: 2, parent_category_id: 614, full_path: "Men's Clothing > Underwear & Night > Briefs"},
  {name: "Long Johns", level: 3, order_index: 3, parent_category_id: 614, full_path: "Men's Clothing > Underwear & Night > Long Johns"},
  {name: "Men's Sleep & Lounge", level: 3, order_index: 4, parent_category_id: 614, full_path: "Men's Clothing > Underwear & Night > Men's Sleep & Lounge"},
  {name: "Pajama Sets", level: 3, order_index: 5, parent_category_id: 614, full_path: "Men's Clothing > Underwear & Night > Pajama Sets"},
  {name: "Robes", level: 3, order_index: 6, parent_category_id: 614, full_path: "Men's Clothing > Underwear & Night > Robes"},
  {name: "Accessories", level: 2, order_index: 5, parent_category_id: 592, full_path: "Men's Clothing > Accessories"},
  {name: "Scarves", level: 3, order_index: 1, parent_category_id: 621, full_path: "Men's Clothing > Accessories > Scarves"},
  {name: "Skullies & Beanies", level: 3, order_index: 2, parent_category_id: 621, full_path: "Men's Clothing > Accessories > Skullies & Beanies"},
  {name: "Prescription Glasses", level: 3, order_index: 3, parent_category_id: 621, full_path: "Men's Clothing > Accessories > Prescription Glasses"},
  {name: "Gloves & Mittens", level: 3, order_index: 4, parent_category_id: 621, full_path: "Men's Clothing > Accessories > Gloves & Mittens"},
  {name: "Belts", level: 3, order_index: 5, parent_category_id: 621, full_path: "Men's Clothing > Accessories > Belts"},
  {name: "Bomber Hats", level: 3, order_index: 6, parent_category_id: 621, full_path: "Men's Clothing > Accessories > Bomber Hats"},
  {name: "Fedoras", level: 3, order_index: 7, parent_category_id: 621, full_path: "Men's Clothing > Accessories > Fedoras"},
  {name: "Berets", level: 3, order_index: 8, parent_category_id: 621, full_path: "Men's Clothing > Accessories > Berets"},
  {name: "Baseball Caps", level: 3, order_index: 9, parent_category_id: 621, full_path: "Men's Clothing > Accessories > Baseball Caps"},
  {name: "Novelty & Special Use", level: 2, order_index: 6, parent_category_id: 592, full_path: "Men's Clothing > Novelty & Special Use"},
  {name: "Cosplay Costumes", level: 3, order_index: 1, parent_category_id: 631, full_path: "Men's Clothing > Novelty & Special Use > Cosplay Costumes"},
  {name: "Stage & Dance Wear", level: 3, order_index: 2, parent_category_id: 631, full_path: "Men's Clothing > Novelty & Special Use > Stage & Dance Wear"},
  {name: "Exotic Apparel", level: 3, order_index: 3, parent_category_id: 631, full_path: "Men's Clothing > Novelty & Special Use > Exotic Apparel"},
  {name: "Bags & Shoes", level: 1, order_index: 1, parent_category_id: nil, full_path: "Bags & Shoes"},
  {name: "Women's Luggage & Bags", level: 2, order_index: 1, parent_category_id: 635, full_path: "Bags & Shoes > Women's Luggage & Bags"},
  {name: "Fashion Backpacks", level: 3, order_index: 1, parent_category_id: 636, full_path: "Bags & Shoes > Women's Luggage & Bags > Fashion Backpacks"},
  {name: "Totes", level: 3, order_index: 2, parent_category_id: 636, full_path: "Bags & Shoes > Women's Luggage & Bags > Totes"},
  {name: "Shoulder Bags", level: 3, order_index: 3, parent_category_id: 636, full_path: "Bags & Shoes > Women's Luggage & Bags > Shoulder Bags"},
  {name: "Wallets", level: 3, order_index: 4, parent_category_id: 636, full_path: "Bags & Shoes > Women's Luggage & Bags > Wallets"},
  {name: "Evening Bags", level: 3, order_index: 5, parent_category_id: 636, full_path: "Bags & Shoes > Women's Luggage & Bags > Evening Bags"},
  {name: "Clutches", level: 3, order_index: 6, parent_category_id: 636, full_path: "Bags & Shoes > Women's Luggage & Bags > Clutches"},
  {name: "Women's Shoes", level: 2, order_index: 2, parent_category_id: 635, full_path: "Bags & Shoes > Women's Shoes"},
  {name: "Women's Sandals", level: 3, order_index: 1, parent_category_id: 643, full_path: "Bags & Shoes > Women's Shoes > Women's Sandals"},
  {name: "Flats", level: 3, order_index: 2, parent_category_id: 643, full_path: "Bags & Shoes > Women's Shoes > Flats"},
  {name: "Heels", level: 3, order_index: 3, parent_category_id: 643, full_path: "Bags & Shoes > Women's Shoes > Heels"},
  {name: "Vulcanized Shoes", level: 3, order_index: 4, parent_category_id: 643, full_path: "Bags & Shoes > Women's Shoes > Vulcanized Shoes"},
  {name: "House slippers", level: 3, order_index: 5, parent_category_id: 643, full_path: "Bags & Shoes > Women's Shoes > House slippers"},
  {name: "Boots", level: 3, order_index: 6, parent_category_id: 643, full_path: "Bags & Shoes > Women's Shoes > Boots"},
  {name: "Men's Luggage & Bags", level: 2, order_index: 3, parent_category_id: 635, full_path: "Bags & Shoes > Men's Luggage & Bags"},
  {name: "Men's Backpacks", level: 3, order_index: 1, parent_category_id: 650, full_path: "Bags & Shoes > Men's Luggage & Bags > Men's Backpacks"},
  {name: "Crossbody Bags", level: 3, order_index: 2, parent_category_id: 650, full_path: "Bags & Shoes > Men's Luggage & Bags > Crossbody Bags"},
  {name: "Briefcases", level: 3, order_index: 3, parent_category_id: 650, full_path: "Bags & Shoes > Men's Luggage & Bags > Briefcases"},
  {name: "Luggage & Travel Bags", level: 3, order_index: 4, parent_category_id: 650, full_path: "Bags & Shoes > Men's Luggage & Bags > Luggage & Travel Bags"},
  {name: "Wallets", level: 3, order_index: 5, parent_category_id: 650, full_path: "Bags & Shoes > Men's Luggage & Bags > Wallets"},
  {name: "Men's Shoes", level: 2, order_index: 4, parent_category_id: 635, full_path: "Bags & Shoes > Men's Shoes"},
  {name: "Casual Shoes", level: 3, order_index: 1, parent_category_id: 656, full_path: "Bags & Shoes > Men's Shoes > Casual Shoes"},
  {name: "Vulcanized Shoes", level: 3, order_index: 2, parent_category_id: 656, full_path: "Bags & Shoes > Men's Shoes > Vulcanized Shoes"},
  {name: "Men's Sandals", level: 3, order_index: 3, parent_category_id: 656, full_path: "Bags & Shoes > Men's Shoes > Men's Sandals"},
  {name: "Loafers", level: 3, order_index: 4, parent_category_id: 656, full_path: "Bags & Shoes > Men's Shoes > Loafers"},
  {name: "Flip Flops", level: 3, order_index: 5, parent_category_id: 656, full_path: "Bags & Shoes > Men's Shoes > Flip Flops"},
  {name: "Boots", level: 3, order_index: 6, parent_category_id: 656, full_path: "Bags & Shoes > Men's Shoes > Boots"},
  {name: "Other Bags & Accessories", level: 2, order_index: 5, parent_category_id: 635, full_path: "Bags & Shoes > Other Bags & Accessories"},
  {name: "Kids & Baby Bags", level: 3, order_index: 1, parent_category_id: 663, full_path: "Bags & Shoes > Other Bags & Accessories > Kids & Baby Bags"},
  {name: "Cosmetic Bags & Cases", level: 3, order_index: 2, parent_category_id: 663, full_path: "Bags & Shoes > Other Bags & Accessories > Cosmetic Bags & Cases"},
  {name: "Coin Purses & Holders", level: 3, order_index: 3, parent_category_id: 663, full_path: "Bags & Shoes > Other Bags & Accessories > Coin Purses & Holders"},
  {name: "Luggage Cover", level: 3, order_index: 4, parent_category_id: 663, full_path: "Bags & Shoes > Other Bags & Accessories > Luggage Cover"},
  {name: "Passport Covers", level: 3, order_index: 5, parent_category_id: 663, full_path: "Bags & Shoes > Other Bags & Accessories > Passport Covers"},
  {name: "Bag Parts & Accessories", level: 3, order_index: 6, parent_category_id: 663, full_path: "Bags & Shoes > Other Bags & Accessories > Bag Parts & Accessories"},
  {name: "Best Selling Shoes", level: 2, order_index: 6, parent_category_id: 635, full_path: "Bags & Shoes > Best Selling Shoes"},
  {name: "Wedge Sandals", level: 3, order_index: 1, parent_category_id: 670, full_path: "Bags & Shoes > Best Selling Shoes > Wedge Sandals"},
  {name: "Classic Pumps", level: 3, order_index: 2, parent_category_id: 670, full_path: "Bags & Shoes > Best Selling Shoes > Classic Pumps"},
  {name: "Large Size Flats", level: 3, order_index: 3, parent_category_id: 670, full_path: "Bags & Shoes > Best Selling Shoes > Large Size Flats"},
  {name: "Indoor Slippers", level: 3, order_index: 4, parent_category_id: 670, full_path: "Bags & Shoes > Best Selling Shoes > Indoor Slippers"},
  {name: "Fashion Sneakers", level: 3, order_index: 5, parent_category_id: 670, full_path: "Bags & Shoes > Best Selling Shoes > Fashion Sneakers"},
  {name: "Comfortable Sandals", level: 3, order_index: 6, parent_category_id: 670, full_path: "Bags & Shoes > Best Selling Shoes > Comfortable Sandals"},
  {name: "Jewelry & Watches", level: 1, order_index: 1, parent_category_id: nil, full_path: "Jewelry & Watches"},
  {name: "Fine Jewelry", level: 2, order_index: 1, parent_category_id: 677, full_path: "Jewelry & Watches > Fine Jewelry"},
  {name: "925 Silver Jewelry", level: 3, order_index: 1, parent_category_id: 678, full_path: "Jewelry & Watches > Fine Jewelry > 925 Silver Jewelry"},
  {name: "Diamond Jewelry", level: 3, order_index: 2, parent_category_id: 678, full_path: "Jewelry & Watches > Fine Jewelry > Diamond Jewelry"},
  {name: "Pearls Jewelry", level: 3, order_index: 3, parent_category_id: 678, full_path: "Jewelry & Watches > Fine Jewelry > Pearls Jewelry"},
  {name: "Various Gemstones", level: 3, order_index: 4, parent_category_id: 678, full_path: "Jewelry & Watches > Fine Jewelry > Various Gemstones"},
  {name: "K-Gold", level: 3, order_index: 5, parent_category_id: 678, full_path: "Jewelry & Watches > Fine Jewelry > K-Gold"},
  {name: "Fine Earrings", level: 3, order_index: 6, parent_category_id: 678, full_path: "Jewelry & Watches > Fine Jewelry > Fine Earrings"},
  {name: "Fine Jewelry Sets", level: 3, order_index: 7, parent_category_id: 678, full_path: "Jewelry & Watches > Fine Jewelry > Fine Jewelry Sets"},
  {name: "Men's Fine Jewelry", level: 3, order_index: 8, parent_category_id: 678, full_path: "Jewelry & Watches > Fine Jewelry > Men's Fine Jewelry"},
  {name: "Wedding & Engagement", level: 2, order_index: 2, parent_category_id: 677, full_path: "Jewelry & Watches > Wedding & Engagement"},
  {name: "Bridal Jewelry Sets", level: 3, order_index: 1, parent_category_id: 687, full_path: "Jewelry & Watches > Wedding & Engagement > Bridal Jewelry Sets"},
  {name: "Engagement Rings", level: 3, order_index: 2, parent_category_id: 687, full_path: "Jewelry & Watches > Wedding & Engagement > Engagement Rings"},
  {name: "Wedding Hair Jewelry", level: 3, order_index: 3, parent_category_id: 687, full_path: "Jewelry & Watches > Wedding & Engagement > Wedding Hair Jewelry"},
  {name: "Men's Watches", level: 2, order_index: 3, parent_category_id: 677, full_path: "Jewelry & Watches > Men's Watches"},
  {name: "Mechanical Watches", level: 3, order_index: 1, parent_category_id: 691, full_path: "Jewelry & Watches > Men's Watches > Mechanical Watches"},
  {name: "Quartz Watches", level: 3, order_index: 2, parent_category_id: 691, full_path: "Jewelry & Watches > Men's Watches > Quartz Watches"},
  {name: "Digital Watches", level: 3, order_index: 3, parent_category_id: 691, full_path: "Jewelry & Watches > Men's Watches > Digital Watches"},
  {name: "Dual Display Watches", level: 3, order_index: 4, parent_category_id: 691, full_path: "Jewelry & Watches > Men's Watches > Dual Display Watches"},
  {name: "Sports Watches", level: 3, order_index: 7, parent_category_id: 691, full_path: "Jewelry & Watches > Men's Watches > Sports Watches"},
  {name: "Women's Watches", level: 3, order_index: 6, parent_category_id: 691, full_path: "Jewelry & Watches > Men's Watches > Women's Watches"},
  {name: "Women's Bracelet Watches", level: 2, order_index: 4, parent_category_id: 677, full_path: "Jewelry & Watches > Women's Bracelet Watches"},
  {name: "Dress Watches", level: 3, order_index: 1, parent_category_id: 698, full_path: "Jewelry & Watches > Women's Bracelet Watches > Dress Watches"},
  {name: "Lovers' Watches", level: 3, order_index: 2, parent_category_id: 698, full_path: "Jewelry & Watches > Women's Bracelet Watches > Lovers' Watches"},
  {name: "Children's Watches", level: 3, order_index: 3, parent_category_id: 698, full_path: "Jewelry & Watches > Women's Bracelet Watches > Children's Watches"},
  {name: "Creative Watches", level: 3, order_index: 4, parent_category_id: 698, full_path: "Jewelry & Watches > Women's Bracelet Watches > Creative Watches"},
  {name: "Fashion Jewelry", level: 2, order_index: 5, parent_category_id: 677, full_path: "Jewelry & Watches > Fashion Jewelry"},
  {name: "Necklaces & Pendants", level: 3, order_index: 1, parent_category_id: 703, full_path: "Jewelry & Watches > Fashion Jewelry > Necklaces & Pendants"},
  {name: "Hot Rings", level: 3, order_index: 2, parent_category_id: 703, full_path: "Jewelry & Watches > Fashion Jewelry > Hot Rings"},
  {name: "Trendy Earrings", level: 3, order_index: 3, parent_category_id: 703, full_path: "Jewelry & Watches > Fashion Jewelry > Trendy Earrings"},
  {name: "Bracelets & Bangles", level: 3, order_index: 4, parent_category_id: 703, full_path: "Jewelry & Watches > Fashion Jewelry > Bracelets & Bangles"},
  {name: "Men's Cuff Links", level: 3, order_index: 5, parent_category_id: 703, full_path: "Jewelry & Watches > Fashion Jewelry > Men's Cuff Links"},
  {name: "Fashion Jewelry Sets", level: 3, order_index: 6, parent_category_id: 703, full_path: "Jewelry & Watches > Fashion Jewelry > Fashion Jewelry Sets"},
  {name: "Charms", level: 3, order_index: 7, parent_category_id: 703, full_path: "Jewelry & Watches > Fashion Jewelry > Charms"},
  {name: "Body Jewelry", level: 3, order_index: 8, parent_category_id: 703, full_path: "Jewelry & Watches > Fashion Jewelry > Body Jewelry"},
  {name: "Beads & DIY Jewelry", level: 2, order_index: 6, parent_category_id: 677, full_path: "Jewelry & Watches > Beads & DIY Jewelry"},
  {name: "Beads", level: 3, order_index: 1, parent_category_id: 712, full_path: "Jewelry & Watches > Beads & DIY Jewelry > Beads"},
  {name: "Jewelry Findings & Components", level: 3, order_index: 2, parent_category_id: 712, full_path: "Jewelry & Watches > Beads & DIY Jewelry > Jewelry Findings & Components"},
  {name: "Jewelry Packaging & Display", level: 3, order_index: 3, parent_category_id: 712, full_path: "Jewelry & Watches > Beads & DIY Jewelry > Jewelry Packaging & Display"},
  {name: "Cellphones & Accessories", level: 1, order_index: 1, parent_category_id: nil, full_path: "Cellphones & Accessories"},
  {name: "Mobile Phones", level: 2, order_index: 1, parent_category_id: 716, full_path: "Cellphones & Accessories > Mobile Phones"},
  {name: "Front Camera", level: 3, order_index: 1, parent_category_id: 717, full_path: "Cellphones & Accessories > Mobile Phones > Front Camera"},
  {name: "Fingerprint Recognition", level: 3, order_index: 2, parent_category_id: 717, full_path: "Cellphones & Accessories > Mobile Phones > Fingerprint Recognition"},
  {name: "Touch Screen", level: 3, order_index: 3, parent_category_id: 717, full_path: "Cellphones & Accessories > Mobile Phones > Touch Screen"},
  {name: "Dual SIM Card", level: 3, order_index: 4, parent_category_id: 717, full_path: "Cellphones & Accessories > Mobile Phones > Dual SIM Card"},
  {name: "6GB RAM", level: 3, order_index: 5, parent_category_id: 717, full_path: "Cellphones & Accessories > Mobile Phones > 6GB RAM"},
  {name: "5.7-inch Display", level: 3, order_index: 6, parent_category_id: 717, full_path: "Cellphones & Accessories > Mobile Phones > 5.7-inch Display"},
  {name: "Mobile Phone Parts", level: 2, order_index: 2, parent_category_id: 716, full_path: "Cellphones & Accessories > Mobile Phone Parts"},
  {name: "Mobile Phone LCDs", level: 3, order_index: 1, parent_category_id: 724, full_path: "Cellphones & Accessories > Mobile Phone Parts > Mobile Phone LCDs"},
  {name: "Mobile Phone Batteries", level: 3, order_index: 2, parent_category_id: 724, full_path: "Cellphones & Accessories > Mobile Phone Parts > Mobile Phone Batteries"},
  {name: "Mobile Phone Housings", level: 3, order_index: 3, parent_category_id: 724, full_path: "Cellphones & Accessories > Mobile Phone Parts > Mobile Phone Housings"},
  {name: "Mobile Phone Touch Panel", level: 3, order_index: 4, parent_category_id: 724, full_path: "Cellphones & Accessories > Mobile Phone Parts > Mobile Phone Touch Panel"},
  {name: "Flex Cables", level: 3, order_index: 5, parent_category_id: 724, full_path: "Cellphones & Accessories > Mobile Phone Parts > Flex Cables"},
  {name: "SIM Card & Tools", level: 3, order_index: 6, parent_category_id: 724, full_path: "Cellphones & Accessories > Mobile Phone Parts > SIM Card & Tools"},
  {name: "Cases & Covers", level: 2, order_index: 3, parent_category_id: 716, full_path: "Cellphones & Accessories > Cases & Covers"},
  {name: "Cases for iPhone XS/XS Max", level: 3, order_index: 1, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases for iPhone XS/XS Max"},
  {name: "Cases For iPhone 8/8 Plus", level: 3, order_index: 2, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases For iPhone 8/8 Plus"},
  {name: "Cases For iPhone 7/7 Plus", level: 3, order_index: 3, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases For iPhone 7/7 Plus"},
  {name: "Cases For iPhone 6/6 Plus", level: 3, order_index: 4, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases For iPhone 6/6 Plus"},
  {name: "Cases For Xiaomi Note 5", level: 3, order_index: 5, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases For Xiaomi Note 5"},
  {name: "Cases For Xiaomi MI 8", level: 3, order_index: 6, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases For Xiaomi MI 8"},
  {name: "Cases For POCOPHONE F1", level: 3, order_index: 7, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases For POCOPHONE F1"},
  {name: "Cases For Samsung S8/S8 Plus", level: 3, order_index: 8, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases For Samsung S8/S8 Plus"},
  {name: "Cases For Samsung S7/S7 Edge", level: 3, order_index: 9, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases For Samsung S7/S7 Edge"},
  {name: "Cases For Huawei P20", level: 3, order_index: 10, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases For Huawei P20"},
  {name: "Cases For Huawei Mate 20", level: 3, order_index: 11, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases For Huawei Mate 20"},
  {name: "Cases For OnePlus", level: 3, order_index: 12, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases For OnePlus"},
  {name: "Cases For Meizu", level: 3, order_index: 13, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases For Meizu"},
  {name: "Cases For OPPO", level: 3, order_index: 14, parent_category_id: 731, full_path: "Cellphones & Accessories > Cases & Covers > Cases For OPPO"},
  {name: "Mobile Phone Accessories", level: 2, order_index: 4, parent_category_id: 716, full_path: "Cellphones & Accessories > Mobile Phone Accessories"},
  {name: "Power Bank", level: 3, order_index: 1, parent_category_id: 746, full_path: "Cellphones & Accessories > Mobile Phone Accessories > Power Bank"},
  {name: "Screen Protectors", level: 3, order_index: 2, parent_category_id: 746, full_path: "Cellphones & Accessories > Mobile Phone Accessories > Screen Protectors"},
  {name: "Mobile Phone Cables", level: 3, order_index: 3, parent_category_id: 746, full_path: "Cellphones & Accessories > Mobile Phone Accessories > Mobile Phone Cables"},
  {name: "Mobile Phone Chargers", level: 3, order_index: 4, parent_category_id: 746, full_path: "Cellphones & Accessories > Mobile Phone Accessories > Mobile Phone Chargers"},
  {name: "Holders & Stands", level: 3, order_index: 5, parent_category_id: 746, full_path: "Cellphones & Accessories > Mobile Phone Accessories > Holders & Stands"},
  {name: "Mobile Phone Lenses", level: 3, order_index: 6, parent_category_id: 746, full_path: "Cellphones & Accessories > Mobile Phone Accessories > Mobile Phone Lenses"},
  {name: "Hot Categories", level: 2, order_index: 5, parent_category_id: 716, full_path: "Cellphones & Accessories > Hot Categories"},
  {name: "Wireless Charger", level: 3, order_index: 1, parent_category_id: 753, full_path: "Cellphones & Accessories > Hot Categories > Wireless Charger"},
  {name: "Car Holder", level: 3, order_index: 2, parent_category_id: 753, full_path: "Cellphones & Accessories > Hot Categories > Car Holder"},
  {name: "Type-C Cables", level: 3, order_index: 3, parent_category_id: 753, full_path: "Cellphones & Accessories > Hot Categories > Type-C Cables"},
  {name: "iPhone Cables", level: 3, order_index: 4, parent_category_id: 753, full_path: "Cellphones & Accessories > Hot Categories > iPhone Cables"},
  {name: "External Batteries", level: 3, order_index: 5, parent_category_id: 753, full_path: "Cellphones & Accessories > Hot Categories > External Batteries"},
  {name: "Car Chargers", level: 3, order_index: 6, parent_category_id: 753, full_path: "Cellphones & Accessories > Hot Categories > Car Chargers"},
  {name: "Computer, Office, Security", level: 1, order_index: 1, parent_category_id: nil, full_path: "Computer, Office, Security"},
  {name: "Components & Peripherals", level: 2, order_index: 1, parent_category_id: 760, full_path: "Computer, Office, Security > Components & Peripherals"},
  {name: "CPUs", level: 3, order_index: 1, parent_category_id: 761, full_path: "Computer, Office, Security > Components & Peripherals > CPUs"},
  {name: "Motherboards", level: 3, order_index: 2, parent_category_id: 761, full_path: "Computer, Office, Security > Components & Peripherals > Motherboards"},
  {name: "Graphics Cards", level: 3, order_index: 3, parent_category_id: 761, full_path: "Computer, Office, Security > Components & Peripherals > Graphics Cards"},
  {name: "Mice", level: 3, order_index: 4, parent_category_id: 761, full_path: "Computer, Office, Security > Components & Peripherals > Mice"},
  {name: "Keyboards", level: 3, order_index: 5, parent_category_id: 761, full_path: "Computer, Office, Security > Components & Peripherals > Keyboards"},
  {name: "Tablet & Laptop Accessories", level: 2, order_index: 2, parent_category_id: 760, full_path: "Computer, Office, Security > Tablet & Laptop Accessories"},
  {name: "Tablets", level: 3, order_index: 1, parent_category_id: 767, full_path: "Computer, Office, Security > Tablet & Laptop Accessories > Tablets"},
  {name: "Laptops", level: 3, order_index: 2, parent_category_id: 767, full_path: "Computer, Office, Security > Tablet & Laptop Accessories > Laptops"},
  {name: "Laptop Bags & Cases", level: 3, order_index: 3, parent_category_id: 767, full_path: "Computer, Office, Security > Tablet & Laptop Accessories > Laptop Bags & Cases"},
  {name: "Tablet LCD Screens", level: 3, order_index: 4, parent_category_id: 767, full_path: "Computer, Office, Security > Tablet & Laptop Accessories > Tablet LCD Screens"},
  {name: "Tablet Cases", level: 3, order_index: 5, parent_category_id: 767, full_path: "Computer, Office, Security > Tablet & Laptop Accessories > Tablet Cases"},
  {name: "Security & Protection", level: 2, order_index: 3, parent_category_id: 760, full_path: "Computer, Office, Security > Security & Protection"},
  {name: "Surveillance Products", level: 3, order_index: 1, parent_category_id: 773, full_path: "Computer, Office, Security > Security & Protection > Surveillance Products"},
  {name: "Access Control", level: 3, order_index: 2, parent_category_id: 773, full_path: "Computer, Office, Security > Security & Protection > Access Control"},
  {name: "Fire Protection", level: 3, order_index: 3, parent_category_id: 773, full_path: "Computer, Office, Security > Security & Protection > Fire Protection"},
  {name: "Workplace Safety Supplies", level: 3, order_index: 4, parent_category_id: 773, full_path: "Computer, Office, Security > Security & Protection > Workplace Safety Supplies"},
  {name: "Alarm & Sensor", level: 3, order_index: 5, parent_category_id: 773, full_path: "Computer, Office, Security > Security & Protection > Alarm & Sensor"},
  {name: "Door Intercom", level: 3, order_index: 6, parent_category_id: 773, full_path: "Computer, Office, Security > Security & Protection > Door Intercom"},
  {name: "Storage Devices", level: 2, order_index: 4, parent_category_id: 760, full_path: "Computer, Office, Security > Storage Devices"},
  {name: "USB Flash Drives", level: 3, order_index: 1, parent_category_id: 780, full_path: "Computer, Office, Security > Storage Devices > USB Flash Drives"},
  {name: "Memory Cards", level: 3, order_index: 2, parent_category_id: 780, full_path: "Computer, Office, Security > Storage Devices > Memory Cards"},
  {name: "External Hard Drives", level: 3, order_index: 3, parent_category_id: 780, full_path: "Computer, Office, Security > Storage Devices > External Hard Drives"},
  {name: "HDD Enclosures", level: 3, order_index: 4, parent_category_id: 780, full_path: "Computer, Office, Security > Storage Devices > HDD Enclosures"},
  {name: "SSD", level: 3, order_index: 5, parent_category_id: 780, full_path: "Computer, Office, Security > Storage Devices > SSD"},
  {name: "Office Electronics", level: 2, order_index: 5, parent_category_id: 760, full_path: "Computer, Office, Security > Office Electronics"},
  {name: "Printer Supplies", level: 3, order_index: 1, parent_category_id: 786, full_path: "Computer, Office, Security > Office Electronics > Printer Supplies"},
  {name: "Office & School Supplies", level: 3, order_index: 2, parent_category_id: 786, full_path: "Computer, Office, Security > Office Electronics > Office & School Supplies"},
  {name: "3D Printers", level: 3, order_index: 3, parent_category_id: 786, full_path: "Computer, Office, Security > Office Electronics > 3D Printers"},
  {name: "Printers", level: 3, order_index: 4, parent_category_id: 786, full_path: "Computer, Office, Security > Office Electronics > Printers"},
  {name: "Scanners", level: 3, order_index: 5, parent_category_id: 786, full_path: "Computer, Office, Security > Office Electronics > Scanners"},
  {name: "3D Pens", level: 3, order_index: 6, parent_category_id: 786, full_path: "Computer, Office, Security > Office Electronics > 3D Pens"},
  {name: "Networking", level: 2, order_index: 6, parent_category_id: 760, full_path: "Computer, Office, Security > Networking"},
  {name: "Wireless Routers", level: 3, order_index: 1, parent_category_id: 793, full_path: "Computer, Office, Security > Networking > Wireless Routers"},
  {name: "Network Cards", level: 3, order_index: 2, parent_category_id: 793, full_path: "Computer, Office, Security > Networking > Network Cards"},
  {name: "3G Modems", level: 3, order_index: 3, parent_category_id: 793, full_path: "Computer, Office, Security > Networking > 3G Modems"},
  {name: "Modem-Router Combos", level: 3, order_index: 4, parent_category_id: 793, full_path: "Computer, Office, Security > Networking > Modem-Router Combos"},
  {name: "Networking Tools", level: 3, order_index: 5, parent_category_id: 793, full_path: "Computer, Office, Security > Networking > Networking Tools"},
  {name: "Consumer Electronics", level: 1, order_index: 1, parent_category_id: nil, full_path: "Consumer Electronics"},
  {name: "Accessories & Parts", level: 2, order_index: 1, parent_category_id: 799, full_path: "Consumer Electronics > Accessories & Parts"},
  {name: "Digital Cables", level: 3, order_index: 1, parent_category_id: 800, full_path: "Consumer Electronics > Accessories & Parts > Digital Cables"},
  {name: "Electronic Cigarettes", level: 3, order_index: 2, parent_category_id: 800, full_path: "Consumer Electronics > Accessories & Parts > Electronic Cigarettes"},
  {name: "Batteries", level: 3, order_index: 3, parent_category_id: 800, full_path: "Consumer Electronics > Accessories & Parts > Batteries"},
  {name: "Charger", level: 3, order_index: 4, parent_category_id: 800, full_path: "Consumer Electronics > Accessories & Parts > Charger"},
  {name: "Home Electronic Accessories", level: 3, order_index: 5, parent_category_id: 800, full_path: "Consumer Electronics > Accessories & Parts > Home Electronic Accessories"},
  {name: "Digital Gear Bags", level: 3, order_index: 6, parent_category_id: 800, full_path: "Consumer Electronics > Accessories & Parts > Digital Gear Bags"},
  {name: "Home Audio & Video", level: 2, order_index: 2, parent_category_id: 799, full_path: "Consumer Electronics > Home Audio & Video"},
  {name: "Television", level: 3, order_index: 1, parent_category_id: 807, full_path: "Consumer Electronics > Home Audio & Video > Television"},
  {name: "TV Receivers", level: 3, order_index: 2, parent_category_id: 807, full_path: "Consumer Electronics > Home Audio & Video > TV Receivers"},
  {name: "Projectors", level: 3, order_index: 3, parent_category_id: 807, full_path: "Consumer Electronics > Home Audio & Video > Projectors"},
  {name: "Audio Amplifiers", level: 3, order_index: 4, parent_category_id: 807, full_path: "Consumer Electronics > Home Audio & Video > Audio Amplifiers"},
  {name: "TV Sticks", level: 3, order_index: 5, parent_category_id: 807, full_path: "Consumer Electronics > Home Audio & Video > TV Sticks"},
  {name: "Camera & Photo", level: 2, order_index: 3, parent_category_id: 799, full_path: "Consumer Electronics > Camera & Photo"},
  {name: "Digital Cameras", level: 3, order_index: 1, parent_category_id: 813, full_path: "Consumer Electronics > Camera & Photo > Digital Cameras"},
  {name: "Camcorders", level: 3, order_index: 2, parent_category_id: 813, full_path: "Consumer Electronics > Camera & Photo > Camcorders"},
  {name: "Camera Drones", level: 3, order_index: 3, parent_category_id: 813, full_path: "Consumer Electronics > Camera & Photo > Camera Drones"},
  {name: "Action Cameras", level: 3, order_index: 4, parent_category_id: 813, full_path: "Consumer Electronics > Camera & Photo > Action Cameras"},
  {name: "Photo Studio", level: 3, order_index: 5, parent_category_id: 813, full_path: "Consumer Electronics > Camera & Photo > Photo Studio"},
  {name: "Camera & Photo Accessories", level: 3, order_index: 6, parent_category_id: 813, full_path: "Consumer Electronics > Camera & Photo > Camera & Photo Accessories"},
  {name: "Portable Audio & Video", level: 2, order_index: 4, parent_category_id: 799, full_path: "Consumer Electronics > Portable Audio & Video"},
  {name: "Earphones & Headphones", level: 3, order_index: 1, parent_category_id: 820, full_path: "Consumer Electronics > Portable Audio & Video > Earphones & Headphones"},
  {name: "Speakers", level: 3, order_index: 2, parent_category_id: 820, full_path: "Consumer Electronics > Portable Audio & Video > Speakers"},
  {name: "MP3 Players", level: 3, order_index: 3, parent_category_id: 820, full_path: "Consumer Electronics > Portable Audio & Video > MP3 Players"},
  {name: "Microphones", level: 3, order_index: 4, parent_category_id: 820, full_path: "Consumer Electronics > Portable Audio & Video > Microphones"},
  {name: "VR/AR Devices", level: 3, order_index: 5, parent_category_id: 820, full_path: "Consumer Electronics > Portable Audio & Video > VR/AR Devices"},
  {name: "Smart Electronics", level: 2, order_index: 5, parent_category_id: 799, full_path: "Consumer Electronics > Smart Electronics"},
  {name: "Wearable Devices", level: 3, order_index: 1, parent_category_id: 826, full_path: "Consumer Electronics > Smart Electronics > Wearable Devices"},
  {name: "Smart Home Appliances", level: 3, order_index: 2, parent_category_id: 826, full_path: "Consumer Electronics > Smart Electronics > Smart Home Appliances"},
  {name: "Smart Wearable Accessories", level: 3, order_index: 3, parent_category_id: 826, full_path: "Consumer Electronics > Smart Electronics > Smart Wearable Accessories"},
  {name: "Smart Remote Controls", level: 3, order_index: 4, parent_category_id: 826, full_path: "Consumer Electronics > Smart Electronics > Smart Remote Controls"},
  {name: "Smart Watches", level: 3, order_index: 5, parent_category_id: 826, full_path: "Consumer Electronics > Smart Electronics > Smart Watches"},
  {name: "Smart Wristbands", level: 3, order_index: 6, parent_category_id: 826, full_path: "Consumer Electronics > Smart Electronics > Smart Wristbands"},
  {name: "Video Games", level: 2, order_index: 6, parent_category_id: 799, full_path: "Consumer Electronics > Video Games"},
  {name: "Handheld Game Players", level: 3, order_index: 1, parent_category_id: 833, full_path: "Consumer Electronics > Video Games > Handheld Game Players"},
  {name: "Gamepads", level: 3, order_index: 2, parent_category_id: 833, full_path: "Consumer Electronics > Video Games > Gamepads"},
  {name: "Joysticks", level: 3, order_index: 3, parent_category_id: 833, full_path: "Consumer Electronics > Video Games > Joysticks"},
  {name: "Stickers", level: 3, order_index: 4, parent_category_id: 833, full_path: "Consumer Electronics > Video Games > Stickers"},
  {name: "Beauty & Health, Hair", level: 1, order_index: 1, parent_category_id: nil, full_path: "Beauty & Health, Hair"},
  {name: "Hair Weaves", level: 2, order_index: 1, parent_category_id: 838, full_path: "Beauty & Health, Hair > Hair Weaves"},
  {name: "Bundles With Closure", level: 3, order_index: 1, parent_category_id: 839, full_path: "Beauty & Health, Hair > Hair Weaves > Bundles With Closure"},
  {name: "3/4 Bundles", level: 3, order_index: 2, parent_category_id: 839, full_path: "Beauty & Health, Hair > Hair Weaves > 3/4 Bundles"},
  {name: "Pre-Colored Weaves", level: 3, order_index: 3, parent_category_id: 839, full_path: "Beauty & Health, Hair > Hair Weaves > Pre-Colored Weaves"},
  {name: "Closures", level: 3, order_index: 4, parent_category_id: 839, full_path: "Beauty & Health, Hair > Hair Weaves > Closures"},
  {name: "Lace Wigs", level: 2, order_index: 2, parent_category_id: 838, full_path: "Beauty & Health, Hair > Lace Wigs"},
  {name: "Lace Front Wigs", level: 3, order_index: 1, parent_category_id: 844, full_path: "Beauty & Health, Hair > Lace Wigs > Lace Front Wigs"},
  {name: "Full Lace Wig", level: 3, order_index: 2, parent_category_id: 844, full_path: "Beauty & Health, Hair > Lace Wigs > Full Lace Wig"},
  {name: "360 Lace Wigs", level: 3, order_index: 3, parent_category_id: 844, full_path: "Beauty & Health, Hair > Lace Wigs > 360 Lace Wigs"},
  {name: "250 Density Lace Wigs", level: 3, order_index: 4, parent_category_id: 844, full_path: "Beauty & Health, Hair > Lace Wigs > 250 Density Lace Wigs"},
  {name: "Synthetic Hair", level: 2, order_index: 3, parent_category_id: 838, full_path: "Beauty & Health, Hair > Synthetic Hair"},
  {name: "Synthetic Lace Wigs", level: 3, order_index: 1, parent_category_id: 849, full_path: "Beauty & Health, Hair > Synthetic Hair > Synthetic Lace Wigs"},
  {name: "Synthetic Weaves", level: 3, order_index: 2, parent_category_id: 849, full_path: "Beauty & Health, Hair > Synthetic Hair > Synthetic Weaves"},
  {name: "Hair Braids", level: 3, order_index: 3, parent_category_id: 849, full_path: "Beauty & Health, Hair > Synthetic Hair > Hair Braids"},
  {name: "Synthetic Extensions", level: 3, order_index: 4, parent_category_id: 849, full_path: "Beauty & Health, Hair > Synthetic Hair > Synthetic Extensions"},
  {name: "Makeup", level: 2, order_index: 4, parent_category_id: 838, full_path: "Beauty & Health, Hair > Makeup"},
  {name: "Eyes", level: 3, order_index: 1, parent_category_id: 854, full_path: "Beauty & Health, Hair > Makeup > Eyes"},
  {name: "Lips", level: 3, order_index: 2, parent_category_id: 854, full_path: "Beauty & Health, Hair > Makeup > Lips"},
  {name: "Face", level: 3, order_index: 3, parent_category_id: 854, full_path: "Beauty & Health, Hair > Makeup > Face"},
  {name: "Makeup Tools", level: 3, order_index: 4, parent_category_id: 854, full_path: "Beauty & Health, Hair > Makeup > Makeup Tools"},
  {name: "Health Care", level: 2, order_index: 5, parent_category_id: 838, full_path: "Beauty & Health, Hair > Health Care"},
  {name: "Massage & Relaxation", level: 3, order_index: 1, parent_category_id: 859, full_path: "Beauty & Health, Hair > Health Care > Massage & Relaxation"},
  {name: "Household Health Monitors", level: 3, order_index: 2, parent_category_id: 859, full_path: "Beauty & Health, Hair > Health Care > Household Health Monitors"},
  {name: "Chinese Medicine", level: 3, order_index: 3, parent_category_id: 859, full_path: "Beauty & Health, Hair > Health Care > Chinese Medicine"},
  {name: "Personal Health Care", level: 3, order_index: 4, parent_category_id: 859, full_path: "Beauty & Health, Hair > Health Care > Personal Health Care"},
  {name: "Skin Care", level: 2, order_index: 6, parent_category_id: 838, full_path: "Beauty & Health, Hair > Skin Care"},
  {name: "Face", level: 3, order_index: 1, parent_category_id: 864, full_path: "Beauty & Health, Hair > Skin Care > Face"},
  {name: "Eyes", level: 3, order_index: 2, parent_category_id: 864, full_path: "Beauty & Health, Hair > Skin Care > Eyes"},
  {name: "Body", level: 3, order_index: 3, parent_category_id: 864, full_path: "Beauty & Health, Hair > Skin Care > Body"},
  {name: "Skin Care Tools", level: 3, order_index: 4, parent_category_id: 864, full_path: "Beauty & Health, Hair > Skin Care > Skin Care Tools"},
  {name: "Nail Art & Tools", level: 2, order_index: 7, parent_category_id: 838, full_path: "Beauty & Health, Hair > Nail Art & Tools"},
  {name: "Nail Gel", level: 3, order_index: 1, parent_category_id: 869, full_path: "Beauty & Health, Hair > Nail Art & Tools > Nail Gel"},
  {name: "Nail Drill", level: 3, order_index: 2, parent_category_id: 869, full_path: "Beauty & Health, Hair > Nail Art & Tools > Nail Drill"},
  {name: "Nail Dryer", level: 3, order_index: 3, parent_category_id: 869, full_path: "Beauty & Health, Hair > Nail Art & Tools > Nail Dryer"},
  {name: "Nail Glitter", level: 3, order_index: 4, parent_category_id: 869, full_path: "Beauty & Health, Hair > Nail Art & Tools > Nail Glitter"},
  {name: "Personal Care", level: 2, order_index: 8, parent_category_id: 838, full_path: "Beauty & Health, Hair > Personal Care"},
  {name: "Hair Care & Styling", level: 3, order_index: 1, parent_category_id: 874, full_path: "Beauty & Health, Hair > Personal Care > Hair Care & Styling"},
  {name: "Shaving & Hair Removal", level: 3, order_index: 2, parent_category_id: 874, full_path: "Beauty & Health, Hair > Personal Care > Shaving & Hair Removal"},
  {name: "Oral Hygiene", level: 3, order_index: 3, parent_category_id: 874, full_path: "Beauty & Health, Hair > Personal Care > Oral Hygiene"},
  {name: "Tattoo & Body Art", level: 2, order_index: 9, parent_category_id: 838, full_path: "Beauty & Health, Hair > Tattoo & Body Art"},
  {name: "Tattoo Kits", level: 3, order_index: 1, parent_category_id: 878, full_path: "Beauty & Health, Hair > Tattoo & Body Art > Tattoo Kits"},
  {name: "Sex Products", level: 2, order_index: 10, parent_category_id: 838, full_path: "Beauty & Health, Hair > Sex Products"},
  {name: "Condoms", level: 3, order_index: 1, parent_category_id: 880, full_path: "Beauty & Health, Hair > Sex Products > Condoms"},
  {name: "Lubricants", level: 3, order_index: 2, parent_category_id: 880, full_path: "Beauty & Health, Hair > Sex Products > Lubricants"},
  {name: "Vibrators", level: 3, order_index: 3, parent_category_id: 880, full_path: "Beauty & Health, Hair > Sex Products > Vibrators"},
  {name: "Home & Garden, Appliance", level: 1, order_index: 1, parent_category_id: nil, full_path: "Home & Garden, Appliance"},
  {name: "Arts", level: 2, order_index: 1, parent_category_id: 884, full_path: "Home & Garden, Appliance > Arts"},
  {name: "DIY Apparel Sewing & Fabric", level: 3, order_index: 1, parent_category_id: 885, full_path: "Home & Garden, Appliance > Arts > DIY Apparel Sewing & Fabric"},
  {name: "Needle Arts & Craft", level: 3, order_index: 2, parent_category_id: 885, full_path: "Home & Garden, Appliance > Arts > Needle Arts & Craft"},
  {name: "Scrapbook & Stamping", level: 3, order_index: 3, parent_category_id: 885, full_path: "Home & Garden, Appliance > Arts > Scrapbook & Stamping"},
  {name: "5D DIY Diamond Painting", level: 3, order_index: 4, parent_category_id: 885, full_path: "Home & Garden, Appliance > Arts > 5D DIY Diamond Painting"},
  {name: "Home Decor", level: 2, order_index: 2, parent_category_id: 884, full_path: "Home & Garden, Appliance > Home Decor"},
  {name: "Painting & Calligraphy", level: 3, order_index: 1, parent_category_id: 890, full_path: "Home & Garden, Appliance > Home Decor > Painting & Calligraphy"},
  {name: "Wall Stickers", level: 3, order_index: 2, parent_category_id: 890, full_path: "Home & Garden, Appliance > Home Decor > Wall Stickers"},
  {name: "Figurines & Miniatures", level: 3, order_index: 3, parent_category_id: 890, full_path: "Home & Garden, Appliance > Home Decor > Figurines & Miniatures"},
  {name: "Wall Clocks", level: 3, order_index: 4, parent_category_id: 890, full_path: "Home & Garden, Appliance > Home Decor > Wall Clocks"},
  {name: "Home Textile", level: 2, order_index: 3, parent_category_id: 884, full_path: "Home & Garden, Appliance > Home Textile"},
  {name: "Cushions", level: 3, order_index: 1, parent_category_id: 895, full_path: "Home & Garden, Appliance > Home Textile > Cushions"},
  {name: "Curtains", level: 3, order_index: 2, parent_category_id: 895, full_path: "Home & Garden, Appliance > Home Textile > Curtains"},
  {name: "Bedding Set", level: 3, order_index: 3, parent_category_id: 895, full_path: "Home & Garden, Appliance > Home Textile > Bedding Set"},
  {name: "Beach Towels", level: 3, order_index: 4, parent_category_id: 895, full_path: "Home & Garden, Appliance > Home Textile > Beach Towels"},
  {name: "Festival", level: 2, order_index: 4, parent_category_id: 884, full_path: "Home & Garden, Appliance > Festival"},
  {name: "Event & Party", level: 3, order_index: 1, parent_category_id: 900, full_path: "Home & Garden, Appliance > Festival > Event & Party"},
  {name: "Ballons", level: 3, order_index: 2, parent_category_id: 900, full_path: "Home & Garden, Appliance > Festival > Ballons"},
  {name: "Artificial & Dried Flowers", level: 3, order_index: 3, parent_category_id: 900, full_path: "Home & Garden, Appliance > Festival > Artificial & Dried Flowers"},
  {name: "Gift Bags & Boxes", level: 3, order_index: 4, parent_category_id: 900, full_path: "Home & Garden, Appliance > Festival > Gift Bags & Boxes"},
  {name: "Home Storage", level: 2, order_index: 5, parent_category_id: 884, full_path: "Home & Garden, Appliance > Home Storage"},
  {name: "Storage Boxes & Bins", level: 3, order_index: 1, parent_category_id: 905, full_path: "Home & Garden, Appliance > Home Storage > Storage Boxes & Bins"},
  {name: "Laundry Baskets", level: 3, order_index: 2, parent_category_id: 905, full_path: "Home & Garden, Appliance > Home Storage > Laundry Baskets"},
  {name: "Drawer Organizers", level: 3, order_index: 3, parent_category_id: 905, full_path: "Home & Garden, Appliance > Home Storage > Drawer Organizers"},
  {name: "Makeup Organizers", level: 3, order_index: 4, parent_category_id: 905, full_path: "Home & Garden, Appliance > Home Storage > Makeup Organizers"},
  {name: "Household Merchandises", level: 2, order_index: 6, parent_category_id: 884, full_path: "Home & Garden, Appliance > Household Merchandises"},
  {name: "Umbrellas", level: 3, order_index: 1, parent_category_id: 910, full_path: "Home & Garden, Appliance > Household Merchandises > Umbrellas"},
  {name: "Bathroom Scales", level: 3, order_index: 2, parent_category_id: 910, full_path: "Home & Garden, Appliance > Household Merchandises > Bathroom Scales"},
  {name: "Hand Push Sweepers", level: 3, order_index: 3, parent_category_id: 910, full_path: "Home & Garden, Appliance > Household Merchandises > Hand Push Sweepers"},
  {name: "Dust Covers", level: 3, order_index: 4, parent_category_id: 910, full_path: "Home & Garden, Appliance > Household Merchandises > Dust Covers"},
  {name: "Kitchen", level: 2, order_index: 7, parent_category_id: 884, full_path: "Home & Garden, Appliance > Kitchen"},
  {name: "Bakeware", level: 3, order_index: 1, parent_category_id: 915, full_path: "Home & Garden, Appliance > Kitchen > Bakeware"},
  {name: "Drinkware", level: 3, order_index: 2, parent_category_id: 915, full_path: "Home & Garden, Appliance > Kitchen > Drinkware"},
  {name: "Kitchen Tools & Gadgets", level: 3, order_index: 3, parent_category_id: 915, full_path: "Home & Garden, Appliance > Kitchen > Kitchen Tools & Gadgets"},
  {name: "Kitchen Knives & Accessories", level: 3, order_index: 4, parent_category_id: 915, full_path: "Home & Garden, Appliance > Kitchen > Kitchen Knives & Accessories"},
  {name: "Garden Supplies", level: 2, order_index: 8, parent_category_id: 884, full_path: "Home & Garden, Appliance > Garden Supplies"},
  {name: "Watering Kits", level: 3, order_index: 1, parent_category_id: 920, full_path: "Home & Garden, Appliance > Garden Supplies > Watering Kits"},
  {name: "Flower Pots & Planters", level: 3, order_index: 2, parent_category_id: 920, full_path: "Home & Garden, Appliance > Garden Supplies > Flower Pots & Planters"},
  {name: "Repellents", level: 3, order_index: 3, parent_category_id: 920, full_path: "Home & Garden, Appliance > Garden Supplies > Repellents"},
  {name: "Garden Water Timers", level: 3, order_index: 4, parent_category_id: 920, full_path: "Home & Garden, Appliance > Garden Supplies > Garden Water Timers"},
  {name: "Furniture", level: 2, order_index: 9, parent_category_id: 884, full_path: "Home & Garden, Appliance > Furniture"},
  {name: "Home Furniture", level: 3, order_index: 1, parent_category_id: 925, full_path: "Home & Garden, Appliance > Furniture > Home Furniture"},
  {name: "Office Furniture", level: 3, order_index: 2, parent_category_id: 925, full_path: "Home & Garden, Appliance > Furniture > Office Furniture"},
  {name: "Outdoor Furniture", level: 3, order_index: 3, parent_category_id: 925, full_path: "Home & Garden, Appliance > Furniture > Outdoor Furniture"},
  {name: "Top Furniture Stores", level: 3, order_index: 4, parent_category_id: 925, full_path: "Home & Garden, Appliance > Furniture > Top Furniture Stores"},
  {name: "Toys, Kids & Baby", level: 1, order_index: 1, parent_category_id: nil, full_path: "Toys, Kids & Baby"},
  {name: "Baby Clothing", level: 2, order_index: 1, parent_category_id: 930, full_path: "Toys, Kids & Baby > Baby Clothing"},
  {name: "Baby Dresses", level: 3, order_index: 1, parent_category_id: 931, full_path: "Toys, Kids & Baby > Baby Clothing > Baby Dresses"},
  {name: "Baby  Rompers", level: 3, order_index: 2, parent_category_id: 931, full_path: "Toys, Kids & Baby > Baby Clothing > Baby  Rompers"},
  {name: "Clothing Sets", level: 3, order_index: 3, parent_category_id: 931, full_path: "Toys, Kids & Baby > Baby Clothing > Clothing Sets"},
  {name: "Baby Outerwear", level: 3, order_index: 4, parent_category_id: 931, full_path: "Toys, Kids & Baby > Baby Clothing > Baby Outerwear"},
  {name: "Baby Pants", level: 3, order_index: 5, parent_category_id: 931, full_path: "Toys, Kids & Baby > Baby Clothing > Baby Pants"},
  {name: "Baby Accessories", level: 3, order_index: 6, parent_category_id: 931, full_path: "Toys, Kids & Baby > Baby Clothing > Baby Accessories"},
  {name: "Toys & Hobbies", level: 2, order_index: 2, parent_category_id: 930, full_path: "Toys, Kids & Baby > Toys & Hobbies"},
  {name: "RC Helicopters", level: 3, order_index: 1, parent_category_id: 938, full_path: "Toys, Kids & Baby > Toys & Hobbies > RC Helicopters"},
  {name: "Stuffed & Plush Animals", level: 3, order_index: 2, parent_category_id: 938, full_path: "Toys, Kids & Baby > Toys & Hobbies > Stuffed & Plush Animals"},
  {name: "Action & Toy Figures", level: 3, order_index: 3, parent_category_id: 938, full_path: "Toys, Kids & Baby > Toys & Hobbies > Action & Toy Figures"},
  {name: "Blocks", level: 3, order_index: 4, parent_category_id: 938, full_path: "Toys, Kids & Baby > Toys & Hobbies > Blocks"},
  {name: "Electronic Pets", level: 3, order_index: 5, parent_category_id: 938, full_path: "Toys, Kids & Baby > Toys & Hobbies > Electronic Pets"},
  {name: "Girls Clothing", level: 2, order_index: 3, parent_category_id: 930, full_path: "Toys, Kids & Baby > Girls Clothing"},
  {name: "Dresses", level: 3, order_index: 1, parent_category_id: 944, full_path: "Toys, Kids & Baby > Girls Clothing > Dresses"},
  {name: "Clothing Sets", level: 3, order_index: 2, parent_category_id: 944, full_path: "Toys, Kids & Baby > Girls Clothing > Clothing Sets"},
  {name: "Tops & Tees", level: 3, order_index: 3, parent_category_id: 944, full_path: "Toys, Kids & Baby > Girls Clothing > Tops & Tees"},
  {name: "Sleepwear & Robes", level: 3, order_index: 4, parent_category_id: 944, full_path: "Toys, Kids & Baby > Girls Clothing > Sleepwear & Robes"},
  {name: "Accessories", level: 3, order_index: 5, parent_category_id: 944, full_path: "Toys, Kids & Baby > Girls Clothing > Accessories"},
  {name: "Family Matching Outfits", level: 3, order_index: 6, parent_category_id: 944, full_path: "Toys, Kids & Baby > Girls Clothing > Family Matching Outfits"},
  {name: "Shoes & Bags", level: 2, order_index: 4, parent_category_id: 930, full_path: "Toys, Kids & Baby > Shoes & Bags"},
  {name: "Baby’s First Walkers", level: 3, order_index: 1, parent_category_id: 951, full_path: "Toys, Kids & Baby > Shoes & Bags > Baby’s First Walkers"},
  {name: "Girls' Shoes", level: 3, order_index: 2, parent_category_id: 951, full_path: "Toys, Kids & Baby > Shoes & Bags > Girls' Shoes"},
  {name: "Boys' Shoes", level: 3, order_index: 3, parent_category_id: 951, full_path: "Toys, Kids & Baby > Shoes & Bags > Boys' Shoes"},
  {name: "School Bags", level: 3, order_index: 4, parent_category_id: 951, full_path: "Toys, Kids & Baby > Shoes & Bags > School Bags"},
  {name: "Kids' Wallets", level: 3, order_index: 5, parent_category_id: 951, full_path: "Toys, Kids & Baby > Shoes & Bags > Kids' Wallets"},
  {name: "Boys Clothing", level: 2, order_index: 5, parent_category_id: 930, full_path: "Toys, Kids & Baby > Boys Clothing"},
  {name: "Clothing Sets", level: 3, order_index: 1, parent_category_id: 957, full_path: "Toys, Kids & Baby > Boys Clothing > Clothing Sets"},
  {name: "T-Shirts", level: 3, order_index: 2, parent_category_id: 957, full_path: "Toys, Kids & Baby > Boys Clothing > T-Shirts"},
  {name: "Hoodies & Sweatshirts", level: 3, order_index: 3, parent_category_id: 957, full_path: "Toys, Kids & Baby > Boys Clothing > Hoodies & Sweatshirts"},
  {name: "Outerwear & Coats", level: 3, order_index: 4, parent_category_id: 957, full_path: "Toys, Kids & Baby > Boys Clothing > Outerwear & Coats"},
  {name: "Jeans", level: 3, order_index: 5, parent_category_id: 957, full_path: "Toys, Kids & Baby > Boys Clothing > Jeans"},
  {name: "Accessories", level: 3, order_index: 6, parent_category_id: 957, full_path: "Toys, Kids & Baby > Boys Clothing > Accessories"},
  {name: "Baby & Mother", level: 2, order_index: 6, parent_category_id: 930, full_path: "Toys, Kids & Baby > Baby & Mother"},
  {name: "Nappy Changing", level: 3, order_index: 1, parent_category_id: 964, full_path: "Toys, Kids & Baby > Baby & Mother > Nappy Changing"},
  {name: "Activity & Gear", level: 3, order_index: 2, parent_category_id: 964, full_path: "Toys, Kids & Baby > Baby & Mother > Activity & Gear"},
  {name: "Baby Care", level: 3, order_index: 3, parent_category_id: 964, full_path: "Toys, Kids & Baby > Baby & Mother > Baby Care"},
  {name: "Backpacks & Carriers", level: 3, order_index: 4, parent_category_id: 964, full_path: "Toys, Kids & Baby > Baby & Mother > Backpacks & Carriers"},
  {name: "Maternity", level: 3, order_index: 5, parent_category_id: 964, full_path: "Toys, Kids & Baby > Baby & Mother > Maternity"},
  {name: "Sports & Outdoors", level: 1, order_index: 1, parent_category_id: nil, full_path: "Sports & Outdoors"},
  {name: "Swimming", level: 2, order_index: 1, parent_category_id: 970, full_path: "Sports & Outdoors > Swimming"},
  {name: "Bikini Set", level: 3, order_index: 1, parent_category_id: 971, full_path: "Sports & Outdoors > Swimming > Bikini Set"},
  {name: "One-Piece Suits", level: 3, order_index: 2, parent_category_id: 971, full_path: "Sports & Outdoors > Swimming > One-Piece Suits"},
  {name: "Two-Piece Suits", level: 3, order_index: 3, parent_category_id: 971, full_path: "Sports & Outdoors > Swimming > Two-Piece Suits"},
  {name: "Cover-Ups", level: 3, order_index: 4, parent_category_id: 971, full_path: "Sports & Outdoors > Swimming > Cover-Ups"},
  {name: "Men's Swimwear", level: 3, order_index: 5, parent_category_id: 971, full_path: "Sports & Outdoors > Swimming > Men's Swimwear"},
  {name: "Children's Swimwear", level: 3, order_index: 6, parent_category_id: 971, full_path: "Sports & Outdoors > Swimming > Children's Swimwear"},
  {name: "Cycling", level: 2, order_index: 2, parent_category_id: 970, full_path: "Sports & Outdoors > Cycling"},
  {name: "Bicycles", level: 3, order_index: 1, parent_category_id: 978, full_path: "Sports & Outdoors > Cycling > Bicycles"},
  {name: "Bicycle Frames", level: 3, order_index: 2, parent_category_id: 978, full_path: "Sports & Outdoors > Cycling > Bicycle Frames"},
  {name: "Bicycle Lights", level: 3, order_index: 3, parent_category_id: 978, full_path: "Sports & Outdoors > Cycling > Bicycle Lights"},
  {name: "Bicycle Helmets", level: 3, order_index: 4, parent_category_id: 978, full_path: "Sports & Outdoors > Cycling > Bicycle Helmets"},
  {name: "Cycling Jerseys", level: 3, order_index: 5, parent_category_id: 978, full_path: "Sports & Outdoors > Cycling > Cycling Jerseys"},
  {name: "Cycling Eyewear", level: 3, order_index: 6, parent_category_id: 978, full_path: "Sports & Outdoors > Cycling > Cycling Eyewear"},
  {name: "Sneakers", level: 2, order_index: 3, parent_category_id: 970, full_path: "Sports & Outdoors > Sneakers"},
  {name: "Running Shoes", level: 3, order_index: 1, parent_category_id: 985, full_path: "Sports & Outdoors > Sneakers > Running Shoes"},
  {name: "Hiking Shoes", level: 3, order_index: 2, parent_category_id: 985, full_path: "Sports & Outdoors > Sneakers > Hiking Shoes"},
  {name: "Soccer Shoes", level: 3, order_index: 3, parent_category_id: 985, full_path: "Sports & Outdoors > Sneakers > Soccer Shoes"},
  {name: "Skateboarding Shoes", level: 3, order_index: 4, parent_category_id: 985, full_path: "Sports & Outdoors > Sneakers > Skateboarding Shoes"},
  {name: "Dance Shoes", level: 3, order_index: 5, parent_category_id: 985, full_path: "Sports & Outdoors > Sneakers > Dance Shoes"},
  {name: "Basketball Shoes", level: 3, order_index: 6, parent_category_id: 985, full_path: "Sports & Outdoors > Sneakers > Basketball Shoes"},
  {name: "Fishing", level: 2, order_index: 4, parent_category_id: 970, full_path: "Sports & Outdoors > Fishing"},
  {name: "Fishing Reels", level: 3, order_index: 1, parent_category_id: 992, full_path: "Sports & Outdoors > Fishing > Fishing Reels"},
  {name: "Fishing Lures", level: 3, order_index: 2, parent_category_id: 992, full_path: "Sports & Outdoors > Fishing > Fishing Lures"},
  {name: "Fishing Lines", level: 3, order_index: 3, parent_category_id: 992, full_path: "Sports & Outdoors > Fishing > Fishing Lines"},
  {name: "Fishing Rods", level: 3, order_index: 4, parent_category_id: 992, full_path: "Sports & Outdoors > Fishing > Fishing Rods"},
  {name: "Rod Combos", level: 3, order_index: 5, parent_category_id: 992, full_path: "Sports & Outdoors > Fishing > Rod Combos"},
  {name: "Fishing Tackle Boxes", level: 3, order_index: 6, parent_category_id: 992, full_path: "Sports & Outdoors > Fishing > Fishing Tackle Boxes"},
  {name: "Sportswear", level: 2, order_index: 5, parent_category_id: 970, full_path: "Sports & Outdoors > Sportswear"},
  {name: "Jerseys", level: 3, order_index: 1, parent_category_id: 999, full_path: "Sports & Outdoors > Sportswear > Jerseys"},
  {name: "Hiking Jackets", level: 3, order_index: 2, parent_category_id: 999, full_path: "Sports & Outdoors > Sportswear > Hiking Jackets"},
  {name: "Pants", level: 3, order_index: 3, parent_category_id: 999, full_path: "Sports & Outdoors > Sportswear > Pants"},
  {name: "Shorts", level: 3, order_index: 4, parent_category_id: 999, full_path: "Sports & Outdoors > Sportswear > Shorts"},
  {name: "Sports Bags", level: 3, order_index: 5, parent_category_id: 999, full_path: "Sports & Outdoors > Sportswear > Sports Bags"},
  {name: "Sports Accessories", level: 3, order_index: 6, parent_category_id: 999, full_path: "Sports & Outdoors > Sportswear > Sports Accessories"},
  {name: "Other Sports Equipment", level: 2, order_index: 6, parent_category_id: 970, full_path: "Sports & Outdoors > Other Sports Equipment"},
  {name: "Camping & Hiking", level: 3, order_index: 1, parent_category_id: 1006, full_path: "Sports & Outdoors > Other Sports Equipment > Camping & Hiking"},
  {name: "Hunting", level: 3, order_index: 2, parent_category_id: 1006, full_path: "Sports & Outdoors > Other Sports Equipment > Hunting"},
  {name: "Golf", level: 3, order_index: 3, parent_category_id: 1006, full_path: "Sports & Outdoors > Other Sports Equipment > Golf"},
  {name: "Fitness & Bodybuilding", level: 3, order_index: 4, parent_category_id: 1006, full_path: "Sports & Outdoors > Other Sports Equipment > Fitness & Bodybuilding"},
  {name: "Skiing & Snowboarding", level: 3, order_index: 5, parent_category_id: 1006, full_path: "Sports & Outdoors > Other Sports Equipment > Skiing & Snowboarding"},
  {name: "Musical Instruments", level: 3, order_index: 6, parent_category_id: 1006, full_path: "Sports & Outdoors > Other Sports Equipment > Musical Instruments"},
  {name: "Automobiles & Motorcycles", level: 1, order_index: 1, parent_category_id: nil, full_path: "Automobiles & Motorcycles"},
  {name: "Auto Replacement Parts", level: 2, order_index: 1, parent_category_id: 1013, full_path: "Automobiles & Motorcycles > Auto Replacement Parts"},
  {name: "Car Lights", level: 3, order_index: 1, parent_category_id: 1014, full_path: "Automobiles & Motorcycles > Auto Replacement Parts > Car Lights"},
  {name: "Interior Parts", level: 3, order_index: 2, parent_category_id: 1014, full_path: "Automobiles & Motorcycles > Auto Replacement Parts > Interior Parts"},
  {name: "Exterior Parts", level: 3, order_index: 3, parent_category_id: 1014, full_path: "Automobiles & Motorcycles > Auto Replacement Parts > Exterior Parts"},
  {name: "Spark Plugs & Ignition System", level: 3, order_index: 4, parent_category_id: 1014, full_path: "Automobiles & Motorcycles > Auto Replacement Parts > Spark Plugs & Ignition System"},
  {name: "Automobiles Sensors", level: 3, order_index: 5, parent_category_id: 1014, full_path: "Automobiles & Motorcycles > Auto Replacement Parts > Automobiles Sensors"},
  {name: "Brake System", level: 3, order_index: 6, parent_category_id: 1014, full_path: "Automobiles & Motorcycles > Auto Replacement Parts > Brake System"},
  {name: "Windscreen Wipers & Windows", level: 3, order_index: 7, parent_category_id: 1014, full_path: "Automobiles & Motorcycles > Auto Replacement Parts > Windscreen Wipers & Windows"},
  {name: "Other Replacement Parts", level: 3, order_index: 8, parent_category_id: 1014, full_path: "Automobiles & Motorcycles > Auto Replacement Parts > Other Replacement Parts"},
  {name: "Tools, Maintenance & Care", level: 2, order_index: 2, parent_category_id: 1013, full_path: "Automobiles & Motorcycles > Tools, Maintenance & Care"},
  {name: "Code Readers & Scan Tools", level: 3, order_index: 1, parent_category_id: 1023, full_path: "Automobiles & Motorcycles > Tools, Maintenance & Care > Code Readers & Scan Tools"},
  {name: "Diagnostic Tools", level: 3, order_index: 2, parent_category_id: 1023, full_path: "Automobiles & Motorcycles > Tools, Maintenance & Care > Diagnostic Tools"},
  {name: "Car Washer", level: 3, order_index: 3, parent_category_id: 1023, full_path: "Automobiles & Motorcycles > Tools, Maintenance & Care > Car Washer"},
  {name: "Paint Care", level: 3, order_index: 4, parent_category_id: 1023, full_path: "Automobiles & Motorcycles > Tools, Maintenance & Care > Paint Care"},
  {name: "Other Maintenance Products", level: 3, order_index: 5, parent_category_id: 1023, full_path: "Automobiles & Motorcycles > Tools, Maintenance & Care > Other Maintenance Products"},
  {name: "Car Electronics", level: 2, order_index: 3, parent_category_id: 1013, full_path: "Automobiles & Motorcycles > Car Electronics"},
  {name: "Car Multimedia Player", level: 3, order_index: 1, parent_category_id: 1029, full_path: "Automobiles & Motorcycles > Car Electronics > Car Multimedia Player"},
  {name: "DVR/Dash Camera", level: 3, order_index: 2, parent_category_id: 1029, full_path: "Automobiles & Motorcycles > Car Electronics > DVR/Dash Camera"},
  {name: "Alarm Systems & Security", level: 3, order_index: 3, parent_category_id: 1029, full_path: "Automobiles & Motorcycles > Car Electronics > Alarm Systems & Security"},
  {name: "GPS Trackers", level: 3, order_index: 4, parent_category_id: 1029, full_path: "Automobiles & Motorcycles > Car Electronics > GPS Trackers"},
  {name: "Car Radios", level: 3, order_index: 5, parent_category_id: 1029, full_path: "Automobiles & Motorcycles > Car Electronics > Car Radios"},
  {name: "Car Monitors", level: 3, order_index: 6, parent_category_id: 1029, full_path: "Automobiles & Motorcycles > Car Electronics > Car Monitors"},
  {name: "Car Refrigerators", level: 3, order_index: 7, parent_category_id: 1029, full_path: "Automobiles & Motorcycles > Car Electronics > Car Refrigerators"},
  {name: "Vehicle Camera", level: 3, order_index: 8, parent_category_id: 1029, full_path: "Automobiles & Motorcycles > Car Electronics > Vehicle Camera"},
  {name: "Vehicle GPS", level: 3, order_index: 9, parent_category_id: 1029, full_path: "Automobiles & Motorcycles > Car Electronics > Vehicle GPS"},
  {name: "Jump Starter", level: 3, order_index: 10, parent_category_id: 1029, full_path: "Automobiles & Motorcycles > Car Electronics > Jump Starter"},
  {name: "Exterior Accessories", level: 2, order_index: 4, parent_category_id: 1013, full_path: "Automobiles & Motorcycles > Exterior Accessories"},
  {name: "Car Stickers", level: 3, order_index: 1, parent_category_id: 1040, full_path: "Automobiles & Motorcycles > Exterior Accessories > Car Stickers"},
  {name: "Car Covers", level: 3, order_index: 2, parent_category_id: 1040, full_path: "Automobiles & Motorcycles > Exterior Accessories > Car Covers"},
  {name: "Other Exterior Accessories", level: 3, order_index: 3, parent_category_id: 1040, full_path: "Automobiles & Motorcycles > Exterior Accessories > Other Exterior Accessories"},
  {name: "Motorcycle Accessories & Parts", level: 2, order_index: 5, parent_category_id: 1013, full_path: "Automobiles & Motorcycles > Motorcycle Accessories & Parts"},
  {name: "Body & Frame", level: 3, order_index: 1, parent_category_id: 1044, full_path: "Automobiles & Motorcycles > Motorcycle Accessories & Parts > Body & Frame"},
  {name: "Helmet & Protective Gear", level: 3, order_index: 2, parent_category_id: 1044, full_path: "Automobiles & Motorcycles > Motorcycle Accessories & Parts > Helmet & Protective Gear"},
  {name: "Lighting", level: 3, order_index: 3, parent_category_id: 1044, full_path: "Automobiles & Motorcycles > Motorcycle Accessories & Parts > Lighting"},
  {name: "Brake System", level: 3, order_index: 4, parent_category_id: 1044, full_path: "Automobiles & Motorcycles > Motorcycle Accessories & Parts > Brake System"},
  {name: "Exhaust & Exhaust Systems", level: 3, order_index: 5, parent_category_id: 1044, full_path: "Automobiles & Motorcycles > Motorcycle Accessories & Parts > Exhaust & Exhaust Systems"},
  {name: "Helmets & Headsets", level: 3, order_index: 6, parent_category_id: 1044, full_path: "Automobiles & Motorcycles > Motorcycle Accessories & Parts > Helmets & Headsets"},
  {name: "Motorcycle Seat Covers", level: 3, order_index: 7, parent_category_id: 1044, full_path: "Automobiles & Motorcycles > Motorcycle Accessories & Parts > Motorcycle Seat Covers"},
  {name: "Other Motorcycle Accessories", level: 3, order_index: 8, parent_category_id: 1044, full_path: "Automobiles & Motorcycles > Motorcycle Accessories & Parts > Other Motorcycle Accessories"},
  {name: "Interior Accessories", level: 2, order_index: 6, parent_category_id: 1013, full_path: "Automobiles & Motorcycles > Interior Accessories"},
  {name: "Seat Covers", level: 3, order_index: 1, parent_category_id: 1053, full_path: "Automobiles & Motorcycles > Interior Accessories > Seat Covers"},
  {name: "Stowing Tidying", level: 3, order_index: 2, parent_category_id: 1053, full_path: "Automobiles & Motorcycles > Interior Accessories > Stowing Tidying"},
  {name: "Car Key Case", level: 3, order_index: 3, parent_category_id: 1053, full_path: "Automobiles & Motorcycles > Interior Accessories > Car Key Case"},
  {name: "Steering Covers", level: 3, order_index: 4, parent_category_id: 1053, full_path: "Automobiles & Motorcycles > Interior Accessories > Steering Covers"},
  {name: "Floor Mats", level: 3, order_index: 5, parent_category_id: 1053, full_path: "Automobiles & Motorcycles > Interior Accessories > Floor Mats"},
  {name: "Home Improvement, Tools", level: 1, order_index: 1, parent_category_id: nil, full_path: "Home Improvement, Tools"},
  {name: "Tools", level: 2, order_index: 3, parent_category_id: 1059, full_path: "Home Improvement, Tools > Tools"},
  {name: "Measurement & Analysis", level: 3, order_index: 1, parent_category_id: 1060, full_path: "Home Improvement, Tools > Tools > Measurement & Analysis"},
  {name: "Hand Tools", level: 3, order_index: 2, parent_category_id: 1060, full_path: "Home Improvement, Tools > Tools > Hand Tools"},
  {name: "Power Tools", level: 3, order_index: 3, parent_category_id: 1060, full_path: "Home Improvement, Tools > Tools > Power Tools"},
  {name: "Garden Tools", level: 3, order_index: 4, parent_category_id: 1060, full_path: "Home Improvement, Tools > Tools > Garden Tools"},
  {name: "Tool Sets", level: 3, order_index: 5, parent_category_id: 1060, full_path: "Home Improvement, Tools > Tools > Tool Sets"},
  {name: "Indoor Lighting", level: 2, order_index: 2, parent_category_id: 1059, full_path: "Home Improvement, Tools > Indoor Lighting"},
  {name: "Ceiling Lights", level: 3, order_index: 1, parent_category_id: 1066, full_path: "Home Improvement, Tools > Indoor Lighting > Ceiling Lights"},
  {name: "Pendant Lights", level: 3, order_index: 2, parent_category_id: 1066, full_path: "Home Improvement, Tools > Indoor Lighting > Pendant Lights"},
  {name: "Downlights", level: 3, order_index: 3, parent_category_id: 1066, full_path: "Home Improvement, Tools > Indoor Lighting > Downlights"},
  {name: "Chandeliers", level: 3, order_index: 4, parent_category_id: 1066, full_path: "Home Improvement, Tools > Indoor Lighting > Chandeliers"},
  {name: "Wall Lamps", level: 3, order_index: 5, parent_category_id: 1066, full_path: "Home Improvement, Tools > Indoor Lighting > Wall Lamps"},
  {name: "Night Lights", level: 3, order_index: 6, parent_category_id: 1066, full_path: "Home Improvement, Tools > Indoor Lighting > Night Lights"},
  {name: "Welding Equipment", level: 3, order_index: 1, parent_category_id: 1060, full_path: "Home Improvement, Tools > Tools > Welding Equipment"},
  {name: "Welding & Soldering Supplies", level: 3, order_index: 2, parent_category_id: 1060, full_path: "Home Improvement, Tools > Tools > Welding & Soldering Supplies"},
  {name: "Machine Tools & Accessories", level: 3, order_index: 3, parent_category_id: 1060, full_path: "Home Improvement, Tools > Tools > Machine Tools & Accessories"},
  {name: "Woodworking Machinery", level: 3, order_index: 4, parent_category_id: 1060, full_path: "Home Improvement, Tools > Tools > Woodworking Machinery"},
  {name: "Tool Storage", level: 3, order_index: 5, parent_category_id: 1060, full_path: "Home Improvement, Tools > Tools > Tool Storage"},
  {name: "LED Lighting", level: 2, order_index: 4, parent_category_id: 1059, full_path: "Home Improvement, Tools > LED Lighting"},
  {name: "LED Strips", level: 3, order_index: 1, parent_category_id: 1078, full_path: "Home Improvement, Tools > LED Lighting > LED Strips"},
  {name: "LED Downlights", level: 3, order_index: 2, parent_category_id: 1078, full_path: "Home Improvement, Tools > LED Lighting > LED Downlights"},
  {name: "LED Panel Lights", level: 3, order_index: 3, parent_category_id: 1078, full_path: "Home Improvement, Tools > LED Lighting > LED Panel Lights"},
  {name: "LED Spotlights", level: 3, order_index: 4, parent_category_id: 1078, full_path: "Home Improvement, Tools > LED Lighting > LED Spotlights"},
  {name: "LED Bar Lights", level: 3, order_index: 5, parent_category_id: 1078, full_path: "Home Improvement, Tools > LED Lighting > LED Bar Lights"},
  {name: "Home Improvements", level: 2, order_index: 5, parent_category_id: 1059, full_path: "Home Improvement, Tools > Home Improvements"},
  {name: "Electrical Equipments & Supplies", level: 3, order_index: 1, parent_category_id: 1084, full_path: "Home Improvement, Tools > Home Improvements > Electrical Equipments & Supplies"},
  {name: "Wall Switches", level: 3, order_index: 2, parent_category_id: 1084, full_path: "Home Improvement, Tools > Home Improvements > Wall Switches"},
  {name: "Hardware", level: 3, order_index: 3, parent_category_id: 1084, full_path: "Home Improvement, Tools > Home Improvements > Hardware"},
  {name: "Kitchen Fixtures", level: 3, order_index: 4, parent_category_id: 1084, full_path: "Home Improvement, Tools > Home Improvements > Kitchen Fixtures"},
  {name: "Paint Tools", level: 3, order_index: 5, parent_category_id: 1084, full_path: "Home Improvement, Tools > Home Improvements > Paint Tools"},
  {name: "Pump", level: 3, order_index: 6, parent_category_id: 1084, full_path: "Home Improvement, Tools > Home Improvements > Pump"},
  {name: "Outdoor Lighting", level: 2, order_index: 6, parent_category_id: 1059, full_path: "Home Improvement, Tools > Outdoor Lighting"},
  {name: "Flashlights & Torches", level: 3, order_index: 1, parent_category_id: 1091, full_path: "Home Improvement, Tools > Outdoor Lighting > Flashlights & Torches"},
  {name: "Solar Lamps", level: 3, order_index: 2, parent_category_id: 1091, full_path: "Home Improvement, Tools > Outdoor Lighting > Solar Lamps"},
  {name: "Floodlights", level: 3, order_index: 3, parent_category_id: 1091, full_path: "Home Improvement, Tools > Outdoor Lighting > Floodlights"},
  {name: "String Lights", level: 3, order_index: 4, parent_category_id: 1091, full_path: "Home Improvement, Tools > Outdoor Lighting > String Lights"},
  {name: "Underwater Lights", level: 3, order_index: 5, parent_category_id: 1091, full_path: "Home Improvement, Tools > Outdoor Lighting > Underwater Lights"}
])
