# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Spree::Core::Engine.load_seed if defined?(Spree::Core)
Spree::Auth::Engine.load_seed if defined?(Spree::Auth)
SolidusMarketplace::Engine.load_seed if defined?(SolidusMarketplace)

######################################
# Seller product management

Spree::OptionType.create!(
    [
        {name: "clothing-size", presentation: "Size", position: 1},
        {name: "clothing-color", presentation: "Color", position: 2},
        {name: "device-color", presentation: "Color", position: 3},
        {name: "style", presentation: "Style", position: 4},
        {name: "condition", presentation: "Condition", position: 5},
        {name: "color", presentation: "Color", position: 6},
        {name: "quality", presentation: "Quality", position: 7},
        {name: "size", presentation: "Size", position: 8},
        {name: "waist", presentation: "Waist", position: 9},
        {name: "age group", presentation: "Age Group", position: 10},
        {name: "age range", presentation: "Age Range", position: 11},
        {name: "air volume", presentation: "Air Volume", position: 12},
        {name: "gender", presentation: "Gender", position: 13},
        {name: "height", presentation: "Height", position: 14},
        {name: "quantity", presentation: "Quantity", position: 15},
        {name: "US size", presentation: "Us Size", position: 16},
        {name: "band color", presentation: "Band Color", position: 17},
        {name: "band length", presentation: "Band Length", position: 18},
        {name: "band material", presentation: "Band Material", position: 19},
        {name: "band size", presentation: "Band Size", position: 20},
        {name: "bandwidth", presentation: "Bandwidth", position: 21},
        {name: "basic frequency", presentation: "Basic Frequency", position: 22},
        {name: "battery capacity", presentation: "Battery Capacity", position: 23},
        {name: "belt width", presentation: "Belt Width", position: 24},
        {name: "bikini type", presentation: "Bikini Type", position: 25},
        {name: "blazer style", presentation: "Blazer Style", position: 26},
        {name: "blazer type", presentation: "Blazer Type", position: 27},
        {name: "blouse length", presentation: "Blouse Length", position: 28},
        {name: "blouse style", presentation: "Blouse Style", position: 29},
        {name: "blouse type", presentation: "Blouse Type", position: 30},
        {name: "bluetooth standard", presentation: "Bluetooth Standard", position: 31},
        {name: "bluetooth version", presentation: "Bluetooth Version", position: 32},
        {name: "body interface", presentation: "Body Interface", position: 33},
        {name: "body material", presentation: "Body Material", position: 34},
        {name: "body shape", presentation: "Body Shape", position: 35},
        {name: "bot height", presentation: "Bot Height", position: 36},
        {name: "bot type", presentation: "Bot Type", position: 37},
        {name: "bracelets type", presentation: "Bracelets Type", position: 38},
        {name: "buckle color", presentation: "Buckle Color", position: 39},
        {name: "buckle length", presentation: "Buckle Length", position: 40},
        {name: "buckle width", presentation: "Buckle Width", position: 41},
        {name: "bust", presentation: "Bust", position: 42},
        {name: "bust style", presentation: "Bust Style", position: 43},
        {name: "bust size", presentation: "Bust Size", position: 44},
        {name: "camera type", presentation: "Camera Type", position: 45},
        {name: "capacity", presentation: "Capacity", position: 46},
        {name: "compatible model", presentation: "Compatible Model", position: 47},
        {name: "cardigan style", presentation: "Cardigan Style", position: 48},
        {name: "cardigan type", presentation: "Cardigan Type", position: 49},
        {name: "case material", presentation: "Case Material", position: 50},
        {name: "case shape", presentation: "Case Shape", position: 51},
        {name: "casual style", presentation: "Casual Style", position: 52},
        {name: "category", presentation: "Category", position: 53},
        {name: "chain length", presentation: "Chain Length", position: 54},
        {name: "chain material", presentation: "Chain Material", position: 55},
        {name: "chain type", presentation: "Chain Type", position: 56},
        {name: "charging interface", presentation: "Charging Interface", position: 57},
        {name: "charging port", presentation: "Charging Port", position: 58},
        {name: "charging voltage", presentation: "Charging Voltage", position: 59},
        {name: "chip model", presentation: "Chip Model", position: 60},
        {name: "closure style", presentation: "Closure Style", position: 61},
        {name: "closure type", presentation: "Closure Type", position: 62},
        {name: "coat length", presentation: "Coat Length", position: 63},
        {name: "coat material", presentation: "Coat Material", position: 64},
        {name: "coat style", presentation: "Coat Style", position: 65},
        {name: "coat type", presentation: "Coat Type", position: 66},
        {name: "code", presentation: "Code", position: 72},
        {name: "colar color", presentation: "Colar Color", position: 73},
        {name: "colar material", presentation: "Colar Material", position: 74},
        {name: "colar shape", presentation: "Colar Shape", position: 75},
        {name: "colar style", presentation: "Colar Style", position: 76},
        {name: "colar type", presentation: "Colar Type", position: 77},
        {name: "colors", presentation: "Colors", position: 85},
        {name: "combination type", presentation: "Combination Type", position: 87},
        {name: "comfort level", presentation: "Comfort Level", position: 88},
        {name: "comunication interface", presentation: "Comunication Interface", position: 89},
        {name: "compatible brand", presentation: "Compatible Brand", position: 90},
        {name: "confirm payment", presentation: "Confirm Payment", position: 92},
        {name: "control level", presentation: "Control Level", position: 93},
        {name: "corset style", presentation: "Corset Style", position: 94},
        {name: "costume style", presentation: "Costume Style", position: 95},
        {name: "costume type", presentation: "Costume Type", position: 96},
        {name: "count", presentation: "Count", position: 98},
        {name: "crop style", presentation: "Crop Style", position: 100},
        {name: "cup shape", presentation: "Cup Shape", position: 105},
        {name: "custom size", presentation: "Custom Size", position: 106},
        {name: "customized shape", presentation: "Customized Shape", position: 107},
        {name: "denim color", presentation: "Denim Color", position: 115},
        {name: "denim fabric", presentation: "Denim Fabric", position: 116},
        {name: "design category", presentation: "Design Category", position: 118},
        {name: "design name", presentation: "Design Name", position: 119},
        {name: "design style", presentation: "Design Style", position: 120},
        {name: "design type", presentation: "Design Type", position: 121},
        {name: "detail size", presentation: "Detail Size", position: 122},
        {name: "dial diameter", presentation: "Dial Diameter", position: 123},
        {name: "diameter", presentation: "Diameter", position: 124},
        {name: "diameter size", presentation: "Diameter Size", position: 125},
        {name: "display color", presentation: "Display Color", position: 126},
        {name: "display size", presentation: "Display Size", position: 127},
        {name: "dot color", presentation: "Dot Color", position: 129},
        {name: "down weight", presentation: "Down Weight", position: 130},
        {name: "earphone color", presentation: "Earphone Color", position: 132},
        {name: "earring color", presentation: "Earring Color", position: 133},
        {name: "earring size", presentation: "Earring Size", position: 134},
        {name: "earring type", presentation: "Earring Type", position: 135},
        {name: "edition", presentation: "Edition", position: 136},
        {name: "edition style", presentation: "Edition Style", position: 137},
        {name: "edition type", presentation: "Edition Type", position: 138},
        {name: "elastic type", presentation: "Elastic Type", position: 139},
        {name: "elasticity fabric", presentation: "Elasticity Fabric", position: 141},
        {name: "elegant style", presentation: "Elegant Style", position: 142},
        {name: "enlarging code", presentation: "Enlarging Code", position: 145},
        {name: "ethnic style", presentation: "Ethnic Style", position: 148},
        {name: "exterior material", presentation: "Exterior Material", position: 158},
        {name: "fabric", presentation: "Fabric", position: 159},
        {name: "fabric material", presentation: "Fabric Material", position: 160},
        {name: "fabric name", presentation: "Fabric Name", position: 161},
        {name: "fabric quality", presentation: "Fabric Quality", position: 162},
        {name: "fabric style", presentation: "Fabric Style", position: 163},
        {name: "fabric type", presentation: "Fabric Type", position: 164},
        {name: "fabric weight", presentation: "Fabric Weight", position: 165},
        {name: "fan life", presentation: "Fan Life", position: 167},
        {name: "fan size", presentation: "Fan Size", position: 168},
        {name: "fashion edition", presentation: "Fashion Edition", position: 169},
        {name: "fashion style", presentation: "Fashion Style", position: 170},
        {name: "fashion type", presentation: "Fashion Type", position: 171},
        {name: "fashionable style", presentation: "Fashionable Style", position: 172},
        {name: "fast charge", presentation: "Fast Charge", position: 173},
        {name: "fit type", presentation: "Fit Type", position: 174},
        {name: "fit age", presentation: "Fit Age", position: 175},
        {name: "fit height", presentation: "Fit Height", position: 176},
        {name: "fit model", presentation: "Fit Model", position: 177},
        {name: "fit season", presentation: "Fit Season", position: 178},
        {name: "fit style", presentation: "Fit Style", position: 179},
        {name: "flexible level", presentation: "Flexible Level", position: 180},
        {name: "focal length", presentation: "Focal Length", position: 182},
        {name: "folk style", presentation: "Folk Style", position: 183},
        {name: "format", presentation: "Format", position: 187},
        {name: "frame material", presentation: "Frame Material", position: 190},
        {name: "frame rate", presentation: "Frame Rate", position: 191},
        {name: "frame type", presentation: "Frame Type", position: 192},
        {name: "freight number", presentation: "Freight Number", position: 194},
        {name: "frequency", presentation: "Frequency", position: 195},
        {name: "frequency response", presentation: "Frequency Response", position: 196},
        {name: "front length", presentation: "Front Length", position: 197},
        {name: "front style", presentation: "Front Style", position: 198},
        {name: "fur color", presentation: "Fur Color", position: 199},
        {name: "fur material", presentation: "Fur Material", position: 200},
        {name: "fur style", presentation: "Fur Style", position: 201},
        {name: "fur type", presentation: "Fur Type", position: 202},
        {name: "garment style", presentation: "Garment Style", position: 203},
        {name: "garment type", presentation: "Garment Type", position: 204},
        {name: "garment version", presentation: "Garment Version", position: 205},
        {name: "gothic style", presentation: "Gothic Style", position: 207},
        {name: "grade", presentation: "Grade", position: 208},
        {name: "group", presentation: "Group", position: 212},
        {name: "hair type", presentation: "Hair Type", position: 214},
        {name: "handle material", presentation: "Handle Material", position: 215},
        {name: "hat material", presentation: "Hat Material", position: 218},
        {name: "hat size", presentation: "Hat Size", position: 219},
        {name: "headscarf size", presentation: "Headscarf Size", position: 220},
        {name: "heatsink material", presentation: "Heatsink Material", position: 221},
        {name: "high waist", presentation: "High Waist", position: 226},
        {name: "hole diameter", presentation: "Hole Diameter", position: 228},
        {name: "hole size", presentation: "Hole Size", position: 229},
        {name: "horizontal length", presentation: "Horizontal Length", position: 230},
        {name: "housing material", presentation: "Housing Material", position: 231},
        {name: "humidification method", presentation: "Humidification Method", position: 232},
        {name: "humidifying capacity", presentation: "Humidifying Capacity", position: 233},
        {name: "image type", presentation: "Image Type", position: 234},
        {name: "inner fabric", presentation: "Inner Fabric", position: 235},
        {name: "inner material", presentation: "Inner Material", position: 236},
        {name: "input voltage", presentation: "Input Voltage", position: 237},
        {name: "inside color", presentation: "Inside Color", position: 238},
        {name: "inside fabric", presentation: "Inside Fabric", position: 239},
        {name: "interface", presentation: "Interface", position: 242},
        {name: "interior material", presentation: "Interior Material", position: 243},
        {name: "inventory type", presentation: "Inventory Type", position: 244},
        {name: "jacket material", presentation: "Jacket Material", position: 263},
        {name: "jacket color", presentation: "Jacket Color", position: 264},
        {name: "jacket name", presentation: "Jacket Name", position: 265},
        {name: "jacket quality", presentation: "Jacket Quality", position: 267},
        {name: "jacket size", presentation: "Jacket Size", position: 268},
        {name: "jacket style", presentation: "Jacket Style", position: 269},
        {name: "jacket type", presentation: "Jacket Type", position: 270},
        {name: "jeans length", presentation: "Jeans Length", position: 274},
        {name: "jeans size", presentation: "Jeans Size", position: 275},
        {name: "jeans style", presentation: "Jeans Style", position: 276},
        {name: "jeans type", presentation: "Jeans Type", position: 277},
        {name: "jumpsuit style", presentation: "Jumpsuit Style", position: 278},
        {name: "jumpsuit type", presentation: "Jumpsuit Type", position: 279},
        {name: "jumpsuit length", presentation: "Jumpsuit Length", position: 280},
        {name: "jumpsuit name", presentation: "Jumpsuit Name", position: 281},
        {name: "jumpsuits color", presentation: "Jumpsuits Color", position: 282},
        {name: "jumpsuits length", presentation: "Jumpsuits Length", position: 283},
        {name: "jumpsuits type", presentation: "Jumpsuits Type", position: 284},
        {name: "kit number", presentation: "Kit Number", position: 287},
        {name: "knit style", presentation: "Knit Style", position: 288},
        {name: "knit type", presentation: "Knit Type", position: 289},
        {name: "knit material", presentation: "Knit Material", position: 290},
        {name: "knit fabric", presentation: "Knit Fabric", position: 291},
        {name: "lace fabric", presentation: "Lace Fabric", position: 295},
        {name: "language mode", presentation: "Language Mode", position: 297},
        {name: "largest size", presentation: "Largest Size", position: 299},
        {name: "laundry method", presentation: "Laundry Method", position: 300},
        {name: "lead time", presentation: "Lead Time", position: 301},
        {name: "leather material", presentation: "Leather Material", position: 302},
        {name: "leather style", presentation: "Leather Style", position: 303},
        {name: "leather type", presentation: "Leather Type", position: 304},
        {name: "leggings style", presentation: "Leggings Style", position: 305},
        {name: "leggings color", presentation: "Leggings Color", position: 306},
        {name: "leggings season", presentation: "Leggings Season", position: 307},
        {name: "leggings size", presentation: "Leggings Size", position: 308},
        {name: "leggings style", presentation: "Leggings Style", position: 309},
        {name: "length", presentation: "Length", position: 310},
        {name: "length style", presentation: "Length Style", position: 311},
        {name: "lens length", presentation: "Lens Length", position: 312},
        {name: "lens material", presentation: "Lens Material", position: 313},
        {name: "limited size", presentation: "Limited Size", position: 316},
        {name: "lumbar type", presentation: "Lumbar Type", position: 336},
        {name: "main color", presentation: "Main Color", position: 339},
        {name: "main colour", presentation: "Main Colour", position: 340},
        {name: "main fabric", presentation: "Main Fabric", position: 341},
        {name: "main material", presentation: "Main Material", position: 342},
        {name: "maintenance mode", presentation: "Maintenance Mode", position: 343},
        {name: "making method", presentation: "Making Method", position: 344},
        {name: "market time", presentation: "Market Time", position: 347},
        {name: "marketing category", presentation: "Marketing Category", position: 348},
        {name: "mask style", presentation: "Mask Style", position: 349},
        {name: "material", presentation: "Material", position: 350},
        {name: "material fabric", presentation: "Material Fabric", position: 351},
        {name: "material grade", presentation: "Material Grade", position: 352},
        {name: "material material", presentation: "Material Material", position: 353},
        {name: "material quality", presentation: "Material Quality", position: 354},
        {name: "material type", presentation: "Material Type", position: 355},
        {name: "materials condition", presentation: "Materials Condition", position: 356},
        {name: "maximum frame rate", presentation: "Maximum Frame Rate", position: 357},
        {name: "maximum size", presentation: "Maximum Size", position: 358},
        {name: "merchant code", presentation: "Merchant Code", position: 366},
        {name: "merchant number", presentation: "Merchant Number", position: 367},
        {name: "metal color", presentation: "Metal Color", position: 369},
        {name: "metal material", presentation: "Metal Material", position: 370},
        {name: "metal type", presentation: "Metal Type", position: 371},
        {name: "method", presentation: "Method", position: 373},
        {name: "minor fabric", presentation: "Minor Fabric", position: 378},
        {name: "mix color", presentation: "Mix Color", position: 379},
        {name: "mode", presentation: "Mode", position: 380},
        {name: "model", presentation: "Model", position: 382},
        {name: "model number", presentation: "Model Number", position: 383},
        {name: "model code", presentation: "Model Code", position: 384},
        {name: "model name", presentation: "Model Name", position: 385},
        {name: "model no", presentation: "Model No", position: 386},
        {name: "model size", presentation: "Model Size", position: 387},
        {name: "model sku", presentation: "Model Sku", position: 388},
        {name: "model style", presentation: "Model Style", position: 389},
        {name: "model type", presentation: "Model Type", position: 390},
        {name: "modeling category", presentation: "Modeling Category", position: 391},
        {name: "moder number", presentation: "Moder Number", position: 392},
        {name: "module number", presentation: "Module Number", position: 393},
        {name: "more material", presentation: "More Material", position: 394},
        {name: "more size", presentation: "More Size", position: 395},
        {name: "more style", presentation: "More Style", position: 396},
        {name: "movement type", presentation: "Movement Type", position: 397},
        {name: "name", presentation: "Name", position: 400},
        {name: "natural color", presentation: "Natural Color", position: 401},
        {name: "neck style", presentation: "Neck Style", position: 402},
        {name: "neck type", presentation: "Neck Type", position: 403},
        {name: "necklace size", presentation: "Necklace Size", position: 404},
        {name: "necklace type", presentation: "Necklace Type", position: 405},
        {name: "neckline shape", presentation: "Neckline Shape", position: 407},
        {name: "net weight", presentation: "Net Weight", position: 408},
        {name: "network interface", presentation: "Network Interface", position: 409},
        {name: "nozzle material", presentation: "Nozzle Material", position: 413},
        {name: "nozzle size", presentation: "Nozzle Size", position: 414},
        {name: "nubia model", presentation: "Nubia Model", position: 415},
        {name: "number", presentation: "Number", position: 416},
        {name: "online time", presentation: "Online Time", position: 420},
        {name: "open style", presentation: "Open Style", position: 422},
        {name: "opening depth", presentation: "Opening Depth", position: 423},
        {name: "operating condition", presentation: "Operating Condition", position: 424},
        {name: "operating range", presentation: "Operating Range", position: 425},
        {name: "operating system", presentation: "Operating System", position: 426},
        {name: "operation method", presentation: "Operation Method", position: 427},
        {name: "optional color", presentation: "Optional Color", position: 428},
        {name: "optional size", presentation: "Optional Size", position: 429},
        {name: "optional type", presentation: "Optional Type", position: 430},
        {name: "oriental style", presentation: "Oriental Style", position: 432},
        {name: "out material", presentation: "Out Material", position: 441},
        {name: "out style", presentation: "Out Style", position: 442},
        {name: "outer color", presentation: "Outer Color", position: 443},
        {name: "outer diameter", presentation: "Outer Diameter", position: 444},
        {name: "outer type", presentation: "Outer Type", position: 445},
        {name: "outercoat material", presentation: "Outercoat Material", position: 446},
        {name: "outerwear fabric", presentation: "Outerwear Fabric", position: 447},
        {name: "outerwear type", presentation: "Outerwear Type", position: 448},
        {name: "output interface", presentation: "Output Interface", position: 449},
        {name: "output number", presentation: "Output Number", position: 450},
        {name: "outside fabric", presentation: "Outside Fabric", position: 451},
        {name: "outside length", presentation: "Outside Length", position: 452},
        {name: "outwear style", presentation: "Outwear Style", position: 453},
        {name: "outwear type", presentation: "Outwear Type", position: 454},
        {name: "oversized size", presentation: "Oversized Size", position: 455},
        {name: "package size", presentation: "Package Size", position: 456},
        {name: "package type", presentation: "Package Type", position: 457},
        {name: "package weight", presentation: "Package Weight", position: 458},
        {name: "packing size", presentation: "Packing Size", position: 459},
        {name: "palm length", presentation: "Palm Length", position: 461},
        {name: "panties type", presentation: "Panties Type", position: 465},
        {name: "pants color", presentation: "Pants Color", position: 466},
        {name: "pants length", presentation: "Pants Length", position: 467},
        {name: "pants model", presentation: "Pants Model", position: 468},
        {name: "pants size", presentation: "Pants Size", position: 469},
        {name: "pants style", presentation: "Pants Style", position: 470},
        {name: "pants type", presentation: "Pants Type", position: 471},
        {name: "pants waist", presentation: "Pants Waist", position: 472},
        {name: "payment", presentation: "Payment", position: 481},
        {name: "payment method", presentation: "Payment Method", position: 482},
        {name: "pearl shape", presentation: "Pearl Shape", position: 483},
        {name: "pearl type", presentation: "Pearl Type", position: 484},
        {name: "pendant color", presentation: "Pendant Color", position: 486},
        {name: "pendant size", presentation: "Pendant Size", position: 487},
        {name: "phone model", presentation: "Phone Model", position: 489},
        {name: "picture color", presentation: "Picture Color", position: 490},
        {name: "piece style", presentation: "Piece Style", position: 491},
        {name: "placket shape", presentation: "Placket Shape", position: 492},
        {name: "placket type", presentation: "Placket Type", position: 493},
        {name: "plate type", presentation: "Plate Type", position: 494},
        {name: "platform", presentation: "Platform", position: 495},
        {name: "platform height", presentation: "Platform Height", position: 496},
        {name: "plug diameter", presentation: "Plug Diameter", position: 499},
        {name: "plug type", presentation: "Plug Type", position: 500},
        {name: "plus material", presentation: "Plus Material", position: 501},
        {name: "plus size", presentation: "Plus Size", position: 502},
        {name: "polo type", presentation: "Polo Type", position: 503},
        {name: "power interface", presentation: "Power Interface", position: 506},
        {name: "power type", presentation: "Power Type", position: 507},
        {name: "prepare time", presentation: "Prepare Time", position: 508},
        {name: "price", presentation: "Price", position: 509},
        {name: "price grade", presentation: "Price Grade", position: 510},
        {name: "price range", presentation: "Price Range", position: 511},
        {name: "primary color", presentation: "Primary Color", position: 512},
        {name: "print style", presentation: "Print Style", position: 513},
        {name: "printed type", presentation: "Printed Type", position: 514},
        {name: "printing color", presentation: "Printing Color", position: 515},
        {name: "printing style", presentation: "Printing Style", position: 516},
        {name: "printing type", presentation: "Printing Type", position: 517},
        {name: "producing area", presentation: "Producing Area", position: 518},
        {name: "producing mode", presentation: "Producing Mode", position: 519},
        {name: "production area", presentation: "Production Area", position: 534},
        {name: "production capacity", presentation: "Production Capacity", position: 535},
        {name: "production category", presentation: "Production Category", position: 536},
        {name: "production date", presentation: "Production Date", position: 537},
        {name: "production grade", presentation: "Production Grade", position: 538},
        {name: "production method", presentation: "Production Method", position: 539},
        {name: "production name", presentation: "Production Name", position: 540},
        {name: "production time", presentation: "Production Time", position: 541},
        {name: "products category", presentation: "Products Category", position: 542},
        {name: "products code", presentation: "Products Code", position: 543},
        {name: "products condition", presentation: "Products Condition", position: 544},
        {name: "products name", presentation: "Products Name", position: 545},
        {name: "project material", presentation: "Project Material", position: 546},
        {name: "project type", presentation: "Project Type", position: 547},
        {name: "protoccol", presentation: "Protoccol", position: 548},
        {name: "pure color", presentation: "Pure Color", position: 549},
        {name: "raw material", presentation: "Raw Material", position: 554},
        {name: "recomended age", presentation: "Recomended Age", position: 555},
        {name: "record mode", presentation: "Record Mode", position: 556},
        {name: "reference height", presentation: "Reference Height", position: 557},
        {name: "reference season", presentation: "Reference Season", position: 558},
        {name: "reflective color", presentation: "Reflective Color", position: 559},
        {name: "retro style", presentation: "Retro Style", position: 563},
        {name: "ring color", presentation: "Ring Color", position: 564},
        {name: "ring diameter", presentation: "Ring Diameter", position: 565},
        {name: "ring size", presentation: "Ring Size", position: 567},
        {name: "rings color", presentation: "Rings Color", position: 568},
        {name: "rings size", presentation: "Rings Size", position: 569},
        {name: "rise type", presentation: "Rise Type", position: 570},
        {name: "runway style", presentation: "Runway Style", position: 571},
        {name: "rusian size", presentation: "Rusian Size", position: 572},
        {name: "safety level", presentation: "Safety Level", position: 573},
        {name: "sandal type", presentation: "Sandal Type", position: 583},
        {name: "scarf size", presentation: "Scarf Size", position: 584},
        {name: "sealing length", presentation: "Sealing Length", position: 587},
        {name: "season style", presentation: "Season Style", position: 588},
        {name: "season type", presentation: "Season Type", position: 589},
        {name: "security mode", presentation: "Security Mode", position: 590},
        {name: "select size", presentation: "Select Size", position: 591},
        {name: "seling method", presentation: "Seling Method", position: 592},
        {name: "sensitivity", presentation: "Sensitivity", position: 593},
        {name: "sensor brand", presentation: "Sensor Brand", position: 594},
        {name: "sensor size", presentation: "Sensor Size", position: 595},
        {name: "sensor type", presentation: "Sensor Type", position: 596},
        {name: "serial no", presentation: "Serial No", position: 597},
        {name: "series no", presentation: "Series No", position: 598},
        {name: "service material", presentation: "Service Material", position: 599},
        {name: "service rating", presentation: "Service Rating", position: 600},
        {name: "set type", presentation: "Set Type", position: 601},
        {name: "sets color", presentation: "Sets Color", position: 602},
        {name: "sets gender", presentation: "Sets Gender", position: 603},
        {name: "sets length", presentation: "Sets Length", position: 604},
        {name: "sets season", presentation: "Sets Season", position: 605},
        {name: "sets type", presentation: "Sets Type", position: 606},
        {name: "seating type", presentation: "Seating Type", position: 607},
        {name: "shaft height", presentation: "Shaft Height", position: 609},
        {name: "shaft material", presentation: "Shaft Material", position: 610},
        {name: "shalf height", presentation: "Shalf Height", position: 611},
        {name: "shape", presentation: "Shape", position: 612},
        {name: "shape style", presentation: "Shape Style", position: 613},
        {name: "shelf time", presentation: "Shelf Time", position: 615},
        {name: "shirt fabric", presentation: "Shirt Fabric", position: 623},
        {name: "shirt gender", presentation: "Shirt Gender", position: 624},
        {name: "shirt length", presentation: "Shirt Length", position: 625},
        {name: "shirt material", presentation: "Shirt Material", position: 626},
        {name: "shirt season", presentation: "Shirt Season", position: 627},
        {name: "shirt size", presentation: "Shirt Size", position: 628},
        {name: "shirt style", presentation: "Shirt Style", position: 629},
        {name: "shirt type", presentation: "Shirt Type", position: 630},
        {name: "shirt color", presentation: "Shirt Color", position: 631},
        {name: "shoe material", presentation: "Shoe Material", position: 632},
        {name: "shoe size", presentation: "Shoe Size", position: 633},
        {name: "shoe width", presentation: "Shoe Width", position: 634},
        {name: "shoes material", presentation: "Shoes Material", position: 635},
        {name: "shoes size", presentation: "Shoes Size", position: 636},
        {name: "shoes style", presentation: "Shoes Style", position: 637},
        {name: "shoting mode", presentation: "Shoting Mode", position: 638},
        {name: "shop name", presentation: "Shop Name", position: 639},
        {name: "shorts color", presentation: "Shorts Color", position: 643},
        {name: "shorts gender", presentation: "Shorts Gender", position: 644},
        {name: "shorts season", presentation: "Shorts Season", position: 645},
        {name: "shorts size", presentation: "Shorts Size", position: 646},
        {name: "shorts sku", presentation: "Shorts Sku", position: 647},
        {name: "shorts style", presentation: "Shorts Style", position: 648},
        {name: "shoulder material", presentation: "Shoulder Material", position: 649},
        {name: "shoulder width", presentation: "Shoulder Width", position: 650},
        {name: "size length", presentation: "Size Length", position: 653},
        {name: "size standard", presentation: "Size Standard", position: 654},
        {name: "size style", presentation: "Size Style", position: 655},
        {name: "size type", presentation: "Size Type", position: 656},
        {name: "size weight", presentation: "Size Weight", position: 657},
        {name: "sizer type", presentation: "Sizer Type", position: 658},
        {name: "skirt category", presentation: "Skirt Category", position: 661},
        {name: "skirt color", presentation: "Skirt Color", position: 662},
        {name: "skirt gender", presentation: "Skirt Gender", position: 663},
        {name: "skirt length", presentation: "Skirt Length", position: 664},
        {name: "skirt season", presentation: "Skirt Season", position: 665},
        {name: "skirt sku", presentation: "Skirt Sku", position: 666},
        {name: "skirt style", presentation: "Skirt Style", position: 667},
        {name: "skirt type", presentation: "Skirt Type", position: 668},
        {name: "skirts style", presentation: "Skirts Style", position: 669},
        {name: "sku", presentation: "SKU", position: 670},
        {name: "slim waist", presentation: "Slim Waist", position: 677},
        {name: "sliming waist", presentation: "Sliming Waist", position: 678},
        {name: "socks material", presentation: "Socks Material", position: 680},
        {name: "socks style", presentation: "Socks Style", position: 681},
        {name: "sole material", presentation: "Sole Material", position: 682},
        {name: "solid color", presentation: "Solid Color", position: 683},
        {name: "sound style", presentation: "Sound Style", position: 684},
        {name: "source category", presentation: "Source Category", position: 685},
        {name: "source type", presentation: "Source Type", position: 686},
        {name: "sourcing category", presentation: "Sourcing Category", position: 687},
        {name: "special size", presentation: "Special Size", position: 688},
        {name: "specific material", presentation: "Specific Material", position: 689},
        {name: "sport type", presentation: "Sport Type", position: 690},
        {name: "sport style", presentation: "Sport Style", position: 691},
        {name: "sports type", presentation: "Sports Type", position: 692},
        {name: "sportswear type", presentation: "Sportswear Type", position: 693},
        {name: "standard", presentation: "Standard", position: 694},
        {name: "standby time", presentation: "Standby Time", position: 695},
        {name: "stock color", presentation: "Stock Color", position: 696},
        {name: "stock condition", presentation: "Stock Condition", position: 697},
        {name: "stock size", presentation: "Stock Size", position: 698},
        {name: "stock type", presentation: "Stock Type", position: 699},
        {name: "stockings style", presentation: "Stockings Style", position: 700},
        {name: "stone color", presentation: "Stone Color", position: 701},
        {name: "storage capacity", presentation: "Storage Capacity", position: 703},
        {name: "store name", presentation: "Store Name", position: 704},
        {name: "strap length", presentation: "Strap Length", position: 705},
        {name: "strap type", presentation: "Strap Type", position: 706},
        {name: "style category", presentation: "Style Category", position: 708},
        {name: "style name", presentation: "Style Name", position: 709},
        {name: "style no", presentation: "Style No", position: 710},
        {name: "style number", presentation: "Style Number", position: 711},
        {name: "sub style", presentation: "Sub Style", position: 714},
        {name: "subdivision style", presentation: "Subdivision Style", position: 715},
        {name: "sug size", presentation: "Sug Size", position: 716},
        {name: "suiable season", presentation: "Suiable Season", position: 718},
        {name: "suit age", presentation: "Suit Age", position: 719},
        {name: "suit length", presentation: "Suit Length", position: 720},
        {name: "suit season", presentation: "Suit Season", position: 721},
        {name: "suit style", presentation: "Suit Style", position: 722},
        {name: "suit type", presentation: "Suit Type", position: 723},
        {name: "suitable age", presentation: "Suitable Age", position: 724},
        {name: "suitable group", presentation: "Suitable Group", position: 725},
        {name: "suitable height", presentation: "Suitable Height", position: 726},
        {name: "suitable season", presentation: "Suitable Season", position: 727},
        {name: "suitable size", presentation: "Suitable Size", position: 728},
        {name: "suitable time", presentation: "Suitable Time", position: 729},
        {name: "suitable weight", presentation: "Suitable Weight", position: 730},
        {name: "suite season", presentation: "Suite Season", position: 731},
        {name: "suite style", presentation: "Suite Style", position: 732},
        {name: "suported protocol", presentation: "Suported Protocol", position: 739},
        {name: "suported type", presentation: "Suported Type", position: 740},
        {name: "suported operating system", presentation: "Suported Operating System", position: 741},
        {name: "suported platform", presentation: "Suported Platform", position: 742},
        {name: "sweater color", presentation: "Sweater Color", position: 743},
        {name: "sweater length", presentation: "Sweater Length", position: 744},
        {name: "sweater material", presentation: "Sweater Material", position: 745},
        {name: "sweater season", presentation: "Sweater Season", position: 746},
        {name: "sweater size", presentation: "Sweater Size", position: 747},
        {name: "sweater style", presentation: "Sweater Style", position: 748},
        {name: "sweater type", presentation: "Sweater Type", position: 749},
        {name: "sweater weight", presentation: "Sweater Weight", position: 750},
        {name: "sweaters season", presentation: "Sweaters Season", position: 751},
        {name: "sweaters style", presentation: "Sweaters Style", position: 752},
        {name: "sweaters type", presentation: "Sweaters Type", position: 753},
        {name: "sweaters version", presentation: "Sweaters Version", position: 754},
        {name: "sweatshirt color", presentation: "Sweatshirt Color", position: 755},
        {name: "sweatshirt season", presentation: "Sweatshirt Season", position: 756},
        {name: "sweatshirt size", presentation: "Sweatshirt Size", position: 757},
        {name: "sweatshirt style", presentation: "Sweatshirt Style", position: 758},
        {name: "sweatshirts size", presentation: "Sweatshirts Size", position: 759},
        {name: "sweatshirts style", presentation: "Sweatshirts Style", position: 760},
        {name: "swimsuits type", presentation: "Swimsuits Type", position: 761},
        {name: "swimwear type", presentation: "Swimwear Type", position: 762},
        {name: "tag size", presentation: "Tag Size", position: 763},
        {name: "tank type", presentation: "Tank Type", position: 766},
        {name: "tape type", presentation: "Tape Type", position: 767},
        {name: "ten size", presentation: "Ten Size", position: 768},
        {name: "toe shape", presentation: "Toe Shape", position: 783},
        {name: "top length", presentation: "Top Length", position: 786},
        {name: "top model", presentation: "Top Model", position: 787},
        {name: "top quality", presentation: "Top Quality", position: 788},
        {name: "top style", presentation: "Top Style", position: 789},
        {name: "top type", presentation: "Top Type", position: 790},
        {name: "tops length", presentation: "Tops Length", position: 791},
        {name: "tops name", presentation: "Tops Name", position: 792},
        {name: "tops season", presentation: "Tops Season", position: 793},
        {name: "tops style", presentation: "Tops Style", position: 794},
        {name: "tops type", presentation: "Tops Type", position: 795},
        {name: "total color", presentation: "Total Color", position: 796},
        {name: "total length", presentation: "Total Length", position: 797},
        {name: "tracksuit color", presentation: "Tracksuit Color", position: 798},
        {name: "tracksuit style", presentation: "Tracksuit Style", position: 799},
        {name: "train length", presentation: "Train Length", position: 800},
        {name: "transmision frequency", presentation: "Transmision Frequency", position: 801},
        {name: "transmision rate", presentation: "Transmision Rate", position: 802},
        {name: "transportation method", presentation: "Transportation Method", position: 803},
        {name: "trench style", presentation: "Trench Style", position: 804},
        {name: "trench type", presentation: "Trench Type", position: 805},
        {name: "trench version", presentation: "Trench Version", position: 806},
        {name: "trouser material", presentation: "Trouser Material", position: 807},
        {name: "trouser style", presentation: "Trouser Style", position: 808},
        {name: "trouser type", presentation: "Trouser Type", position: 809},
        {name: "trousers length", presentation: "Trousers Length", position: 810},
        {name: "trousers shape", presentation: "Trousers Shape", position: 811},
        {name: "trousers style", presentation: "Trousers Style", position: 812},
        {name: "trousers type", presentation: "Trousers Type", position: 813},
        {name: "tshirt color", presentation: "Tshirt Color", position: 814},
        {name: "tshirt style", presentation: "Tshirt Style", position: 815},
        {name: "type", presentation: "Type", position: 820},
        {name: "type style", presentation: "Type Style", position: 821},
        {name: "uk size", presentation: "Uk Size", position: 823},
        {name: "uk style", presentation: "Uk Style", position: 824},
        {name: "underwrite size", presentation: "Underwrite Size", position: 825},
        {name: "unit type", presentation: "Unit Type", position: 826},
        {name: "up time", presentation: "Up Time", position: 827},
        {name: "upload time", presentation: "Upload Time", position: 830},
        {name: "us standard", presentation: "Us Standard", position: 833},
        {name: "usb port", presentation: "USB Port", position: 834},
        {name: "use type", presentation: "Use Type", position: 835},
        {name: "velvet fabric", presentation: "Velvet Fabric", position: 838},
        {name: "vent height", presentation: "Vent Height", position: 839},
        {name: "version", presentation: "Version", position: 840},
        {name: "vertical length", presentation: "Vertical Length", position: 843},
        {name: "vest color", presentation: "Vest Color", position: 844},
        {name: "vest material", presentation: "Vest Material", position: 845},
        {name: "vest style", presentation: "Vest Style", position: 846},
        {name: "vest type", presentation: "Vest Type", position: 847},
        {name: "video interface", presentation: "Video Interface", position: 848},
        {name: "view angle", presentation: "View Angle", position: 849},
        {name: "viewing angle", presentation: "Viewing Angle", position: 850},
        {name: "vintage season", presentation: "Vintage Season", position: 851},
        {name: "vintage style", presentation: "Vintage Style", position: 852},
        {name: "vintage type", presentation: "Vintage Type", position: 853},
        {name: "waist height", presentation: "Waist Height", position: 854},
        {name: "waist shape", presentation: "Waist Shape", position: 855},
        {name: "waist size", presentation: "Waist Size", position: 856},
        {name: "waist style", presentation: "Waist Style", position: 857},
        {name: "waist type", presentation: "Waist Type", position: 858},
        {name: "waistline style", presentation: "Waistline Style", position: 859},
        {name: "washing method", presentation: "Washing Method", position: 861},
        {name: "washing mode", presentation: "Washing Mode", position: 862},
        {name: "washing type", presentation: "Washing Type", position: 863},
        {name: "waterproof level", presentation: "Waterproof Level", position: 864},
        {name: "waterproof platform", presentation: "Waterproof Platform", position: 865},
        {name: "weave method", presentation: "Weave Method", position: 873},
        {name: "weaving method", presentation: "Weaving Method", position: 874},
        {name: "weight", presentation: "Weight", position: 875},
        {name: "width", presentation: "Width", position: 878},
        {name: "wiping life", presentation: "Wiping Life", position: 879},
        {name: "wireless protocol", presentation: "Wireless Protocol", position: 880},
        {name: "wireless standard", presentation: "Wireless Standard", position: 881},
        {name: "wireless type", presentation: "Wireless Type", position: 882},
        {name: "working frequency", presentation: "Working Frequency", position: 968},
        {name: "working time", presentation: "Working Time", position: 969},
        {name: "yarn type", presentation: "Yarn Type", position: 970},
        {name: "zone number", presentation: "Zone Number", position: 971},
        {name: "comodity size", presentation: "Comodity Size", position: 972}
    ])